watson-developer-cloud/swift-sdk

WatsonDeveloperCloud/LanguageTranslation/Tests/LanguageTranslationTests.swift
I fixed the issue by checking if model is nil before proceeding with the test. When testing async methods, XCTest enqueue the assertion results, and it fails the test only when *waitForExpectationsWithTimeout(..)* runs. So it is important to not only use *XCTAssertNotNil(...)*, but also stop the async closure if a nil object is found.
I can verify that the same kind of issue is available on other test fixtures. I'll further investigate it and open a new issue for these tests.
=> [language-translation] Check if model is nil when running the test cases #153

WatsonDeveloperCloud/AlchemyLanguage/AlchemyLanguage.swift, WatsonDeveloperCloud/AlchemyLanguage/Tests/AlchemyLanguageTests.swift, WatsonDeveloperCloud/AlchemyVision/Tests/AlchemyVisionTests.swift, WatsonDeveloperCloud/Dialog/Models/DialogConversation.swift, WatsonDeveloperCloud/Dialog/Models/DialogNode.swift, WatsonDeveloperCloud/Dialog/Tests/DialogTests.swift, WatsonDeveloperCloud/LanguageTranslation/Tests/LanguageTranslationTests.swift, WatsonDeveloperCloud/PersonalityInsights/Tests/PersonalityInsightsTests.swift, WatsonDeveloperCloud/SpeechToText/Tests/SpeechToTextTests.swift, WatsonDeveloperCloud/TextToSpeech/Tests/TextToSpeechTests.swift, WatsonDeveloperCloudTests/AuthenticationTests.swift, WatsonDeveloperCloudTests/WatsonDeveloperCloudTests.swift
The `@testable` annotation in Xcode tests allows access to code with the `internal` access modifier. This can hide bugs, since tests pass for models that are `internal` but should be `public`.
By removing the `@testable` annotation, we can be sure that our tests only access the public API of the SDK.
=> Remove testable annotation

WatsonDeveloperCloud/WatsonCore/WatsonGateway.swift
I see that there is no `develop` branch anymore, so I'm requesting to `master`. Please let me know if it's not the right way.
Thanks
=> Removing warning of ++ operator will be deprecated in Swift 3

WatsonDeveloperCloud.xcodeproj/project.pbxproj
This PR removes unnecessary folders from the Xcode project's library search paths. We removed the libopus and libogg libraries with commit 5945837a54db1506ac7fbbce0e4f8236363fa31f, but failed to remove their associated folder from the project's library search paths.
=> Remove unnecessary library search paths

Quickstart.md
This pull request moves the App Transport Security section on the Quickstart page so that these instructions appear earlier.
Addresses issue #196
=> Moved the App Transport Security section up in the Quickstart page

WatsonDeveloperCloud/WatsonCore/Utilities/NetworkUtils.swift, WatsonDeveloperCloud/WatsonCore/WatsonGateway.swift
This pull request adds a user-agent HTTP header to requests made with `WatsonGateway` and `NetworkUtils`. The user agent begins with the string: "watson-developer-cloud-ios-0.2.0" and also contains information about the executable, bundle, version, and OS.
Note that this pull request does NOT add the user-agent to any multipart form uploads, which are executed directly by Alamofire. It also does NOT add the user-agent to the socket used by Speech to Text.
=> Add user agent to WatsonGateway and NetworkUtils

WatsonDeveloperCloud.xcodeproj/project.pbxproj
This PR removes the "Copy Frameworks" build phase, since it is not necessary to have a "Copy Frameworks" build phase in the SDK itself. This may have been causing issue #208. For more information, see the following Carthage issue: Carthage/Carthage#353.
=> Remove "Copy Frameworks" build phase

WatsonDeveloperCloud/SpeechToText/Models/SpeechToTextSettings.swift
profanity filter can be set in settings but it's not sent to the server. so it always takes default value `true`. so there is no way to set profanity filter `false`.
=> missing profanity filter param added

codecov.yml
Let's ignore the code coverage information about our testing suite, since we don't want to test our tests.
Related Issues:
- #156
=> [dev-ops] ignore tests in code coverage

Source/AlchemyVisionV1/AlchemyVision.swift, Source/AlchemyVisionV1/Tests/AlchemyVisionTests.swift
This PR fixes an issue with the `HTMLGetImage` endpoint. The previous code incorrectly formatted the request body. This update fixes that by percent encoding the HTML document before constructing the required body.
#264
=> Fix Alchemy Vision HTML endpoint

Source/AlchemyVisionV1/AlchemyVision.swift, Source/AlchemyVisionV1/Tests/AlchemyVisionTests.swift
This pull request uses assert statements to verify that the results produced by Alchemy Vision's tests match the JSON returned by the service. (Instead of simply assuming that the tests are successful if the response can be deserialized, we now verify that the contents of the response match our expectations.)
Related Issues: #265
=> Verify results of Alchemy Vision tests

Source/AlchemyVisionV1/AlchemyVision.swift, Source/AlchemyVisionV1/Tests/AlchemyVisionTests.swift
This pull request adds negative tests for Alchemy Vision. In particular, it:
- includes a `dataToError` function to convert failure responses to an `NSError` that can be propagated to the user,
- ensures that the `dataToError` function is passed with each `responseObject` serialization call, and
- adds negative tests that exercise the `dataToError` function and ways in which the service may fail.
Related Issues: #266
=> Add negative tests for Alchemy Vision

Source/AlchemyVisionV1/AlchemyVision.swift, Source/AlchemyVisionV1/Tests/AlchemyVisionTests.swift
Using NSURL invokes some trouble with Image Handling. If you choose a Photo from your Camera Roll you get an UIImage or a referencing URL to the Asset. The Initializer NSData(contentsOfURL: ...), which is used in the [API](https://github.com/watson-developer-cloud/ios-sdk/blob/master/Source/AlchemyVisionV1/AlchemyVision.swift#L105), does not handle Asset URLs correctly. 
It seems to me, that NSData reduces a lot of pains for the developers. They can choose what they want to use: Loading from Assets and convert to NSData or transforming UIImage to an UIImagePNGRepresentation and so on.
An other way would be, to use UIImage instead of NSData and make the conversation in the AlchemyVision API.
I am looking forward to your Feedback.
=> Image handling

.github/CONTRIBUTING.md
This pull request updates the [CONTRIBUTING.md](https://github.com/watson-developer-cloud/ios-sdk/blob/master/.github/CONTRIBUTING.md) file to include more information about configuring the `Credentials.plist` file.
=> Update contributing documentation

Source/AlchemyLanguageV1/AlchemyLanguage.swift, Source/AlchemyLanguageV1/Tests/AlchemyLanguageTests.swift
According to the Swift 3 API Design Guidelines: "Acronyms and initialisms that commonly appear as all upper case in American English should be uniformly up- or down-cased according to case conventions."
This change updates the AlchemyLanguage API for better consistency with the Swift 3 API Design Guidelines.
=> Change forUrl to forURL

Source/RelationshipExtractionV1Beta/RelationshipExtraction.swift
This pull request adds a deprecation annotation to Relationship Extraction to alert users to use the AlchemyLanguage service instead.
=> Add deprecation annotation to RelationshipExtraction

Source/AlchemyVisionV1/AlchemyVision.swift
This pull request adds a deprecation annotation to AlchemyVision to alert users to use the Visual Recognition service instead.
=> Add deprecation annotation to AlchemyVision

Source/TextToSpeechV1/Tests/TextToSpeechTests.swift
This PR adds a negative test to synthesize an empty string with the Text to Speech service. This helps document the expected behavior for this scenario (i.e. a 400 error).
=> Add TextToSpeech test for empty string

Documentation/Quickstart.md, README.md, Source/DocumentConversionV1/DocumentConversion.swift
Remove smaterplanet URLs. There is a redirect in place but it's better if we don't rely on it
We moved the documentation from: www.ibm.com/smarterplanet/us/en/ibmwatson/developercloud/
to : www.ibm.com/watson/developercloud/
=> [ci skip] Remove smarterplanet urls

Source/ConversationV1/Models/Context.swift
This pull request changes the `dialogStack` key to `dialog_stack`, as expected by the Conversation service. It fixes a bug where conversation context was not being sufficiently maintained.
=> Fix Conversation bug with dialog stack

Source/AlchemyDataNewsV1/AlchemyDataNews.swift, Source/AlchemyLanguageV1/AlchemyLanguage.swift, Source/AlchemyVisionV1/AlchemyVision.swift, Source/ConversationV1/Conversation.swift, Source/ConversationV1Experimental/Conversation.swift, Source/DialogV1/Dialog.swift, Source/LanguageTranslatorV2/LanguageTranslator.swift, Source/NaturalLanguageClassifierV1/NaturalLanguageClassifier.swift, Source/PersonalityInsightsV2/PersonalityInsights.swift, Source/RelationshipExtractionV1Beta/RelationshipExtraction.swift, Source/RestKit/RestSerialization.swift, Source/RetrieveAndRankV1/RetrieveAndRank.swift, Source/SpeechToTextV1/SpeechToText.swift, Source/TextToSpeechV1/TextToSpeech.swift, Source/ToneAnalyzerV3/ToneAnalyzer.swift, Source/VisualRecognitionV3/VisualRecognition.swift
This pull request updates error handling in RestKit to avoid the use of a `dataToError` function. Instead, any error response is turned into a `String` and included in an `NSError` object.
I removed the `dataToError` function from services where I could. But some services do use the function to check whether an error occurred (for example, when an endpoint would normally return no response, but returns data in the response when an error occurs).
=> Update Error Handling

Source/VisualRecognitionV3/VisualRecognition.swift
While investigating a bug with Visual Recognition I stumbled upon these lines of code in the `writeParameters()` function:
```swift
do {
let data = try JSON.Dictionary(json).serialize()
try data.writeToURL(fileURL, options: .AtomicWrite)
} catch {
// TODO: how to catch this?
}
```
Since the `catch` statement is empty, any errors would silently fail.
This pull request makes the `writeParameters` function throw, and updates all callers to use a do-catch block where the catch block creates and returns an `NSError` object.
=> Catch errors in Visual Recognition

Source/DialogV1/Dialog.swift, Source/DialogV1/Models/Format.swift, Source/DialogV1/Tests/DialogTests.swift
Updated tests and renamed the enums as well
=> Renaming Dialog methods according to Swift 3.0 convention

Source/LanguageTranslatorV2/LanguageTranslator.swift, Source/LanguageTranslatorV2/Tests/LanguageTranslatorTests.swift
Changed a few parameter names for methods and updated tests.
=> Updated Language Translator according to Swift 3.0 naming conventions

Source/SpeechToTextV1/Models/RecognitionSettings.swift
The `ibm.biz` short URLs were broken. This caused broken links in the generated documentation. This pull request fixes the broken links and avoids using shortened URLs (which can make find-and-replace-all difficult).
=> Fix broken links

Source/RestKit/JSON.swift
I think this change will remove the warning messages that appear when building the SDK with Carthage or the Swift Package Manager:
```
/Users/glennfisher/Desktop/Text to Speech/Carthage/Checkouts/ios-sdk/Source/RestKit/JSON.swift:29:27: warning: expression implicitly coerced from 'Any?' to Any
```
=> Add guard let to avoid coercing from Any? to Any

Package.swift, Source/DocumentConversionV1/DocumentConversion.swift, Tests/AlchemyDataNewsV1Tests/AlchemyDataNewsTests.swift, Tests/AlchemyLanguageV1Tests/AlchemyLanguageTests.swift, Tests/AlchemyVisionV1Tests/AlchemyVisionTests.swift, Tests/ConversationV1Tests/ConversationTests.swift, Tests/DialogV1Tests/DialogTests.swift, Tests/DocumentConversionV1Tests/DocumentConversionTests.swift, Tests/LanguageTranslatorV2Tests/LanguageTranslatorTests.swift, Tests/NaturalLanguageClassifierV1Tests/NaturalLanguageClassifierTests.swift, Tests/PersonalityInsightsV2Tests/PersonalityInsightsTests.swift, Tests/RelationshipExtractionV1BetaTests/RelationshipExtractionTests.swift, Tests/RetrieveAndRankV1Tests/RetrieveAndRankTests.swift, Tests/SpeechToTextV1Tests/SpeechToTextTests.swift, Tests/TextToSpeechV1Tests/TextToSpeechTests.swift, Tests/ToneAnalyzerV3Tests/ToneAnalyzerTests.swift, Tests/TradeoffAnalyticsV1Tests/TradeoffAnalyticsTests.swift, Tests/VisualRecognitionV3Tests/VisualRecognitionTests.swift
Ignoring the STT tests, and added in a fix for the Document Conversion errors. Also included Foundation in all the test files.
There's still one more error in Dialog at [this line](https://github.com/watson-developer-cloud/ios-sdk/blob/fix-linux-errors/Tests/DialogV1Tests/DialogTests.swift#L164). Specifically,
```let randomNum = Int(arc4random_uniform(allowedCharsCount))```
=> Fix Linux errors

Source/SpeechToTextV1/SpeechToTextSession.swift
We have occasionally seen an error message related to insufficient data in the audio stream. We suspect it is caused by writing zero bytes to the websocket, which is interpreted by the service as the end of the stream. This commit guards against sending 0 bytes when streaming from the microphone.
Note that users can still use the SpeechToTextSession class and accidentally send a 0-byte Data value. In that case, we want the error to propagate back to the user, which is why we didn’t add these guard statements to the SpeechToTextSocket.writeAudio(audio:) function.
=> Ensure data payload is not empty

Scripts/build-libogg.sh, Scripts/build-libopus.sh
These scripts build the libogg and libopus dependencies for the Speech to Text framework.
They've been sitting around on my desktop, but should really be included in the repository in case we need to rebuild libogg or libopus in the future.
=> Add libogg and libopus build scripts

Source/VisualRecognitionV3/VisualRecognition.swift, Tests/VisualRecognitionV3Tests/VisualRecognitionTests.swift, WatsonDeveloperCloud.xcodeproj/project.pbxproj
This pull request uses a workaround to avoid Xcode optimization for the `car.png` image. With that optimization avoided, it re-enables the functions and tests that upload images to the Visual Recognition service.
All of the Visual Recognition tests passed when executed locally:
=> Upload images with Visual Recognition

Source/SpeechToTextV1/SpeechToText.swift, Source/SpeechToTextV1/SpeechToTextRecorder.swift
After some discussion with Glenn, I moved the lines which call `setCategory` and `setActive` from SpeechToTextSession to SpeechToText. This way, users can use SpeechToText for easy integration of recognizeMicrophone(), and SpeechToTextSession for more control over the AVAudioSession.
This hopefully solves the issue seen in #453.
=> Updating location of AVAudioSession code

Source/TextToSpeechV1/TextToSpeech.swift
If the data returned on to the TextToSpeech synthesize function is
empty, a crash would occur because there was no length checking.
I have signed the Contributor License Agreement.
=> Fix range exceeds data length crash

Source/VisualRecognitionV3/VisualRecognition.swift
Removing CVarArg due to Travis complaints, preventing Travis builds to build properly.
=> Remove CVarArg for travis to build.

Source/RestKit/RestRequest.swift, Source/RestKit/RestToken.swift
This PR adds response methods to RestKit that accept a responseToError function parameter, in place of the dataToError function parameter.  The existing methods with the dataToError function parameter have been retained for compatibility but reimplemented using the new (more general) methods.
The purpose for this change is to allow SDKs to use information from both the response and data objects to identify and describe errors reported by the service. For example, the ErrorResponse (data) for the Conversation service does not contain the HTTP status code, so the Conversation service can now use the responseToError function to extract the HTTP status code from the response for the Error object.
=> Add response methods that support for responseToError functions

Source/RestKit/RestRequest.swift
Add a method to RestKit that returns Void on success.  Some APIs (primarily deletes) return no data -- just a status code indicating success.  The corresponding methods in the SDK should return Void, and this change provides the RestKit support for this.
=> Add responseVoid method to RestKit

.travis.yml, Scripts/run-tests.sh, Tests/DiscoveryV1Tests/DiscoveryTests.swift
3 main changes are included in this PR:
1. Pulled out the `xcodebuild` commands from the `travis.yml` file into a separate `run-tests.sh` script.
2. Updated the iOS10_destination in the travis.yml since the xcode8.3 image on Travis has been updated to xcode 8.3.3, and 10.3.1 is the default iOS 10 version.
3. Updated the Discovery tests to add a class teardown function which deletes the trained environment when all tests finish. This way, the Swift SDK and .NET SDK can properly share credentials for the Discovery service.
=> Refactor our travis.yml file and update Discovery

Tests/AlchemyDataNewsV1Tests/AlchemyDataNewsTests.swift, Tests/AlchemyLanguageV1Tests/AlchemyLanguageTests.swift, Tests/AlchemyVisionV1Tests/AlchemyVisionTests.swift, Tests/ConversationV1Tests/ConversationTests.swift, Tests/DialogV1Tests/DialogTests.swift, Tests/DiscoveryV1Tests/DiscoveryTests.swift, Tests/DocumentConversionV1Tests/DocumentConversionTests.swift, Tests/LanguageTranslatorV2Tests/LanguageTranslatorTests.swift, Tests/NaturalLanguageClassifierV1Tests/NaturalLanguageClassifierTests.swift, Tests/NaturalLanguageUnderstandingV1Tests/NaturalLanguageUnderstandingV1Tests.swift, Tests/PersonalityInsightsV2Tests/PersonalityInsightsTests.swift, Tests/PersonalityInsightsV3Tests/PersonalityInsightsTests.swift, Tests/RelationshipExtractionV1BetaTests/RelationshipExtractionTests.swift, Tests/RetrieveAndRankV1Tests/RetrieveAndRankTests.swift, Tests/SpeechToTextV1Tests/SpeechToTextTests.swift, Tests/TextToSpeechV1Tests/TextToSpeechPlaybackTests.swift, Tests/TextToSpeechV1Tests/TextToSpeechTests.swift, Tests/ToneAnalyzerV3Tests/ToneAnalyzerTests.swift, Tests/TradeoffAnalyticsV1Tests/TradeoffAnalyticsTests.swift, Tests/VisualRecognitionV3Tests/VisualRecognitionTests.swift
This PR sets the default headers in all integration test files so that Swift SDK test activity is not included in usage statistics for Watson services.
=> Set default headers in tests to disable stats collection

README.md, docs/swift-api/services/ConversationV1/docsets/.docset/Contents/Resources/Documents/index.html, docs/swift-api/services/ConversationV1/index.html, docs/swift-api/services/DialogV1/docsets/.docset/Contents/Resources/Documents/index.html, docs/swift-api/services/DialogV1/index.html
Updating links to the WDC site for the Conversation service documentation. It has moved to the Bluemix Docs site. The service landing page also changed. Only updated the index.html pages related to Conversation and Dialog services (not all of them).
=> Updating conversation doc and service landing pages

Source/RestKit/RestToken.swift, Tests/SpeechToTextV1Tests/SpeechToTextTests.swift
Fixes a bug with Speech to Text token authentication.
Previously, users who entered invalid credentials would get a nonsense token. The token was rejected by the Speech to Text service, resulting in a "403 - Invalid HTTP Upgrade" error message. This update ensures that the response from the token url is verified, resulting in a more descriptive error message for invalid credentials.
We may need to communicate this change to other folks working on RestKit.
Closes #655.
=> Parse authentication errors when requesting token

Source/SupportingFiles/Dependencies/ogg/os_types.h, Tests/ConversationV1Tests/ConversationTests.swift, Tests/DiscoveryV1Tests/DiscoveryTests.swift
This pull request adds an `include` statement to fix a bug introduced with Xcode 9. It also includes some test updates for changed behavior.
=> Update for Xcode 9

Source/SpeechToTextV1/Models/SpeechRecognitionEvent.swift, Source/SpeechToTextV1/Models/SpeechRecognitionResults.swift, Source/SpeechToTextV1/SpeechToTextSocket.swift, Tests/SpeechToTextV1Tests/SpeechToTextTests.swift
This pull request fixes a bug with interim speaker labels.
Interim speaker labels were not handled properly because they did not conform to the documented model. That is, the Speech to Text documentation specifies that a `SpeechRecognitionEvent` object will always contain the `resultIndex` and `results` properties, and may optionally contain a `speakerLabels` property. However, when debugging, I received interim speaker labels by themselves, `{ 'speaker_labels': ... }`. The absence of the `resultIndex` and `results` fields caused the JSON parsing to fail, and the speaker labels to be dropped.
This pull request updates the `SpeechRecognitionEvent` and associated code to handle all fields as optional, and process them when they are present.
(I will be reaching out to the Speech to Text team …
=> Handle interim speaker label results

Source/VisualRecognitionV3/VisualRecognition.swift, Tests/VisualRecognitionV3Tests/VisualRecognitionTests.swift
The similarity search operations were [deprecated][1] on September 8. This pull request adds a deprecation notice to the similarity search operations and removes their associated tests.
[1]: https://console.bluemix.net/docs/services/visual-recognition/release-notes.html#release-notes
=> Deprecate similarity search operations

Scripts/build-libogg.sh, Scripts/build-libopus.sh
This pull request updates the build scripts for libogg and libopus. The updated `build-libopus.sh` script was used to build the latest v1.1.3 release of the opus library. The ogg library does not need to be updated, since there has not been a recent release.
=> Update libogg and libopus

Source/SupportingFiles/Dependencies/Starscream/SSLSecurity.swift, Source/SupportingFiles/Dependencies/Starscream/WebSocket.swift
The pull request keeps the WebSocket dependency internal by changing access control specifiers from `public` or `open` to `internal` instead.
=> Internalize the WebSocket dependency

Source/RestKit/JSON.swift, Source/RestKit/RestError.swift
This pull request updates comments based on the `undocumented.json` file produced by the `generate-documentation.sh` script.
Note that there are still some missing documentation comments. Most of them are from `enum` cases within a model (e.g. `CreateDialogNode.NodeType` from Conversation), which contain no documentation in the Swagger specification. Other documentation is missing from Swagger (e.g. `ListModelsResults.models` from Natural Language Understanding) and should be caught by our validator in the future.
=> Fix undocumented code

Source/SpeechToTextV1/Models/SpeechRecognitionEvent.swift
This pull request fixes a bug with Speech to Text:
When a `{"state": "listening"}` message was received, it was interpreted as a `SpeechRecognitionEvent` with all properties set to `nil`. The event was returned to the user, but contained no data.
This pull request requires a `SpeechRecognitionEvent` to have at least one non-null property.
(This may pose a challenge for future code generation, but the Speech to Text service is handwritten for now.)
=> A SpeechRecognitionEvent must have at least one non-null value

Source/SpeechToTextV1/SpeechToTextSocket.swift
This pull request increases the WebSocket timeout from the 5-second default up to 30-seconds. This matches the 30-second [session timeout][1] for the Speech to Text service’s WebSocket interface.
This may help to resolve timeout issues like #693.
[1]: https://console.bluemix.net/docs/services/speech-to-text/websockets.html#WSkeep
=> Increase WebSocket timeout to 30 seconds

Source/SpeechToTextV1/SpeechToText+Recognize.swift, Source/SpeechToTextV1/SpeechToText.swift, Source/SpeechToTextV1/SpeechToTextEncoder.swift, Source/SpeechToTextV1/SpeechToTextRecorder.swift, Source/SpeechToTextV1/SpeechToTextSession.swift, WatsonDeveloperCloud.xcodeproj/project.pbxproj
This pull request uses `#if os(Linux) #else <code> #endif` to identify code that is incompatible with Linux. It also separates the Speech to Text recognition functions into an extension, `SpeechToText+Recognize.swift`.
These changes have two benefits:
1. With conditional compilation, we may be able to support some Speech to Text functionality on Linux. This would be preferable to ignoring the Speech to Text framework altogether.
2. With the recognition functions in a separate extension, the `SpeechToText.swift` file may be easier to generate.
Although this moves us towards support for Speech to Text in the `Package.swift` file, there is more work that needs to be done. In particular, neither Speech to Text nor Text to Speech build with the Swift Package Manager because they depend on …
=> Use conditional compilation blocks to identify Linux incompatibilities

Source/AlchemyLanguageV1/AlchemyLanguage.swift, Source/ConversationV1/Conversation.swift, Source/DialogV1/Dialog.swift, Source/DiscoveryV1/Discovery.swift, Source/DocumentConversionV1/DocumentConversion.swift, Source/LanguageTranslatorV2/LanguageTranslator.swift, Source/NaturalLanguageClassifierV1/NaturalLanguageClassifier.swift, Source/NaturalLanguageUnderstandingV1/NaturalLanguageUnderstanding.swift, Source/PersonalityInsightsV2/PersonalityInsights.swift, Source/PersonalityInsightsV3/PersonalityInsights.swift, Source/RelationshipExtractionV1Beta/RelationshipExtraction.swift, Source/RestKit/RestError.swift, Source/RestKit/RestRequest.swift, Source/RetrieveAndRankV1/RetrieveAndRank.swift, Source/SpeechToTextV1/SpeechToText.swift, Source/TextToSpeechV1/TextToSpeech.swift, Source/ToneAnalyzerV3/ToneAnalyzer.swift, Source/TradeoffAnalyticsV1/TradeoffAnalytics.swift, Tests/RetrieveAndRankV1Tests/RetrieveAndRankTests.swift
Refactor processing in RestKit to move call to parseServiceError down into the core response handling method.  This lays the foundation for simplifying response processing once the legacy Alchemy services are retired.
=> RestKit improvements to response handling

Tests/NaturalLanguageClassifierV1Tests/NaturalLanguageClassifierTests.swift, Tests/NaturalLanguageClassifierV1Tests/trained_meta.txt, Tests/NaturalLanguageClassifierV1Tests/training_meta.txt
This pull request updates the Natural Language Classifier tests to make them easier to read and easier to maintain.
In particular, they no longer try to create and train a classifier when the trained classifier cannot be found. This was causing each test to try creating a classifier. After a couple of executions, the NLC environment would be full and prevent any new classifiers from being created.
The tests are also simpler to read with the removal of obfuscating helper functions. Instead of calling helper functions, the tests now call SDK methods directly.
=> Update Natural Language Classifier Tests

Source/AlchemyDataNewsV1/AlchemyDataNews.swift, Source/AlchemyLanguageV1/AlchemyLanguage.swift, Source/AlchemyVisionV1/AlchemyVision.swift, Source/DialogV1/Dialog.swift, Source/DiscoveryV1/Discovery.swift, Source/DocumentConversionV1/DocumentConversion.swift, Source/LanguageTranslatorV2/LanguageTranslator.swift, Source/PersonalityInsightsV2/PersonalityInsights.swift, Source/PersonalityInsightsV3/PersonalityInsights.swift, Source/RelationshipExtractionV1Beta/RelationshipExtraction.swift, Source/RetrieveAndRankV1/RetrieveAndRank.swift, Source/SpeechToTextV1/SpeechToText+Recognize.swift, Source/SpeechToTextV1/SpeechToText.swift, Source/SpeechToTextV1/SpeechToTextSession.swift, Source/SpeechToTextV1/SpeechToTextSocket.swift, Source/TextToSpeechV1/TextToSpeech.swift, Source/ToneAnalyzerV3/ToneAnalyzer.swift, Source/TradeoffAnalyticsV1/TradeoffAnalytics.swift, Source/VisualRecognitionV3/VisualRecognition.swift
When constructing an `NSError` object, we have commonly used `NSLocalizedFailureReasonErrorKey`. However, this key is not supported well on Linux—the `error.localizedDescription` property on Linux does not check for the failure reason error key.
This pull request replaces instances of `NSLocalizedFailureReasonErrorKey` with `NSLocalizedDescriptionErrorKey`.
=> Use NSLocalizedDescriptionKey

WatsonDeveloperCloud.xcodeproj/project.pbxproj
This pull request fixes a bug caused by `swiftlint` and the `Credentials.swift` symlink that was added to each test directory. The fix is to update how `swiftlint` runs:
- Framework Build Targets: Only lint files inside the `Source/Service/` folder.
- Test Targets: Only lint files inside the `Tests/ServiceTests/` folder.
(Note that test targets depend upon a framework build target. Therefore both folders will end up being linted whenever a test is built.)
The carthage build failed when running `carthage update --platform iOS --no-use-binaries`. It failed because `swiftlint` could not find the `Tests/ServiceTests/Credentials.swift` file.
(Note: `Test/ServiceTests/Credentials.swift` is actually a symlink. The symlink is checked into the repository but the symlink's target is not. As far as …
=> Avoid linting tests in framework targets

Source/ToneAnalyzerV3/Models/DocumentAnalysis.swift, Source/ToneAnalyzerV3/Models/SentenceAnalysis.swift, Source/ToneAnalyzerV3/Models/ToneAnalysis.swift, Source/ToneAnalyzerV3/Models/ToneCategory.swift, Source/ToneAnalyzerV3/Models/ToneChatInput.swift, Source/ToneAnalyzerV3/Models/ToneChatScore.swift, Source/ToneAnalyzerV3/Models/ToneInput.swift, Source/ToneAnalyzerV3/Models/ToneScore.swift, Source/ToneAnalyzerV3/Models/Utterance.swift, Source/ToneAnalyzerV3/Models/UtteranceAnalyses.swift, Source/ToneAnalyzerV3/Models/UtteranceAnalysis.swift, Source/ToneAnalyzerV3/ToneAnalyzer.swift, Tests/ToneAnalyzerV3Tests/ToneAnalyzerTests.swift, WatsonDeveloperCloud.xcodeproj/project.pbxproj
The generated code includes a number of deprecated fields. I am still working on support for deprecation in `watson-swagger-codegen`. I expect to push a new pull request that removes deprecated fields before the major release.
=> Generate Tone Analyzer

Source/AlchemyDataNewsV1/AlchemyDataNews.swift, Source/AlchemyLanguageV1/AlchemyLanguage.swift, Source/AlchemyVisionV1/AlchemyVision.swift, Source/RestKit/RestRequest.swift, Source/VisualRecognitionV3/VisualRecognition.swift, WatsonDeveloperCloud.xcodeproj/project.pbxproj
This pull request allows RestKit to manage API keys.
- The API key implementation is inspired by the [Swagger definition for api keys](https://swagger.io/docs/specification/2-0/authentication/api-keys/).
(API keys must specify `in: .header` or `in: .query` and the `name` of the parameter.)
- I updated services using API keys to ensure that the tests pass, although that code will all be removed soon. 🔥
- We should consider the behavior of `RestRequest` to be _undefined_ when there are conflicting parameters with the same name.
- Example: Passing `Credentials.apiKey(name: "x-api-key", key: "foo", in: .header)` and `headerParameters["x-api-key"] = "bar"` would conflict. So it is _undefined_ whether the x-api-key header parameter will be set to foo or bar.
- The implementation happens to …
=> Add RestKit support for API keys

Source/VisualRecognitionV3/VisualRecognition+UIImage.swift, Tests/ToneAnalyzerV3Tests/ToneAnalyzerTests.swift, Tests/VisualRecognitionV3Tests/VisualRecognition+UIImageTests.swift
This pull request adds some minor fixes.
The changes for `UIKit` are required for compatibility with the Swift Package Manager:
- The `UIKit` import was implicit on iOS, but it's good to make it explicit.
- `UIKit` (and `UIImage` by extension) are not actually supported on macOS. So instead of excluding Linux we should include iOS, tvOS, and watchOS platforms.
=> Add minor fixes

README.md
This pull request updates the readme section for setting custom service urls.
=> Update readme section for custom service urls

Source/AssistantV1/Assistant.swift, Source/AssistantV1/Models/Context.swift, Source/AssistantV1/Models/Counterexample.swift, Source/AssistantV1/Models/DialogNode.swift, Source/AssistantV1/Models/Entity.swift, Source/AssistantV1/Models/EntityExport.swift, Source/AssistantV1/Models/Example.swift, Source/AssistantV1/Models/Intent.swift, Source/AssistantV1/Models/IntentExport.swift, Source/AssistantV1/Models/Synonym.swift, Source/AssistantV1/Models/Value.swift, Source/AssistantV1/Models/ValueExport.swift, Source/AssistantV1/Models/Workspace.swift, Source/AssistantV1/Models/WorkspaceExport.swift, Tests/AssistantV1Tests/AssistantTests.swift
This pull request defines the `created` and `updated` properties to be optional. This is consistent with the `2018-02-16` release of the Assistant service.
The tests also pass when the service date is set to `2017-05-26`.
=> Fix created/updated dates in Assistant service

Source/RestKit/RestError.swift
This pull request changes the description of a `RestError.serializationError`. This change has two benefits:
1. It hides the underlying representation of value(s) as JSON, rather than leaking that representation to users.
2. It allows us to use this error whenever we are serializing a value, even if that value is not actually JSON, e.g. `guard let foo.data(using: .utf8) else { throw RestError.serializationError }`
=> Update description of RestError.serializationError

.swiftlint.yml
Cleaning up `swiftlint.yml`, which I missed in #760.
=> Remove deprecated services from .swiftlint.yml

.travis.yml, Scripts/run-tests.sh, Source/RestKit/JSON.swift, Source/RestKit/RestUtilities.swift, Tests/AssistantV1Tests/AssistantTests.swift, Tests/ConversationV1Tests/ConversationTests.swift, Tests/DiscoveryV1Tests/DiscoveryTests.swift, Tests/VisualRecognitionV3Tests/VisualRecognition+UIImageTests.swift, Tests/VisualRecognitionV3Tests/VisualRecognitionTests.swift, WatsonDeveloperCloud.xcodeproj/project.pbxproj, WatsonDeveloperCloud.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, WatsonDeveloperCloud.xcodeproj/xcshareddata/xcschemes/AssistantV1.xcscheme, WatsonDeveloperCloud.xcodeproj/xcshareddata/xcschemes/ConversationV1.xcscheme, WatsonDeveloperCloud.xcodeproj/xcshareddata/xcschemes/DiscoveryV1.xcscheme, WatsonDeveloperCloud.xcodeproj/xcshareddata/xcschemes/LanguageTranslatorV2.xcscheme, WatsonDeveloperCloud.xcodeproj/xcshareddata/xcschemes/NaturalLanguageClassifierV1.xcscheme, WatsonDeveloperCloud.xcodeproj/xcshareddata/xcschemes/NaturalLanguageUnderstandingV1.xcscheme, WatsonDeveloperCloud.xcodeproj/xcshareddata/xcschemes/PersonalityInsightsV3.xcscheme, WatsonDeveloperCloud.xcodeproj/xcshareddata/xcschemes/RestKit.xcscheme, WatsonDeveloperCloud.xcodeproj/xcshareddata/xcschemes/SpeechToTextV1.xcscheme, WatsonDeveloperCloud.xcodeproj/xcshareddata/xcschemes/TextToSpeechV1.xcscheme, WatsonDeveloperCloud.xcodeproj/xcshareddata/xcschemes/ToneAnalyzerV3.xcscheme, WatsonDeveloperCloud.xcodeproj/xcshareddata/xcschemes/VisualRecognitionV3.xcscheme
Fixes build errors and warnings introduced by Swift 4.1 and Xcode 9.3.
- There were a number of new `identifier_name` errors with SwiftLint. I don't understand why these only popped up with Xcode 9.3, but I fixed them or added a comment to ignore them.
- Xcode 9.3 has a couple new recommended project settings, which I applied to `WatsonDeveloperCloud.xcodeproj`.
- Previously, the `CoreML` library was implicitly linked with the `VisualRecognitionV3Tests` target. Now, Xcode 9.3 requires the `CoreML` library to be explicitly linked in the build phases tab.
=> Update to Swift 4.1 / Xcode 9.3

Cartfile, Cartfile.resolved
This pull request updates the `Cartfile` to point to a newer version of Starscream. The newer version resolves some build warnings that appear when running `carthage update --platform iOS`.
The latest [Starscream release][0] (as of this comment) is 3.0.4. Unfortunately, the 3.0.4 release causes build warnings with Xcode 9.3 (see [this issue][1] for more details).
So I temporarily changed the `Cartfile` to explicitly reference commit `31f522155a4d6323cd1aaefb8dbc140ced7be1ca`. It removes the recursive dependencies `common-crypto-spm` and `zlib-spm`, which were causing the build warnings but weren't actually required.
Once a >3.0.5 release has been published with those changes, we can revert the `Cartfile` back to `~> 3.0` to make sure that new releases will be used by the Swift SDK. But in …
=> Update Starscream dependency

.swiftlint.yml
A `superfluous_disable_command` should not cause the build to fail. Instead, it should only be a warning.
Since SwiftLint interprets identifier names differently between Xcode 9.2 and Xcode 9.3, we added `swiftlint:disable` comments to resolve `identifier_name` errors.
However, SwiftLint does not identify those same errors when using Xcode 9.2. Instead, SwiftLint fails the build with a `superfluous_disable_command` error. The build shouldn't fail because of a comment!
This may resolve issue #791, where the build failed without a reasonable explanation. The user was on Xcode 9.2 and may have had SwiftLint installed, resulting in a failed `run script` that blocked the build.
=> Decrease severity of superfluous_disable_command

.swiftlint.yml, Source/DiscoveryV1/Discovery.swift, Source/DiscoveryV1/Models/QueryAggregation.swift, Source/SpeechToTextV1/Models/RecognitionSettings.swift, Source/TextToSpeechV1/TextToSpeechDecoder.swift
Disable the SwiftLint style rule for `cyclomatic_complexity`.
The `cyclomatic_complexity` rule checks for the number of paths through any given code block. In particular it is triggered by lots of `if` statements or `switch` statements, since lots of branches can make code difficult to understand.
However, this rule is commonly triggered by generated operations with many optional query parameters. There is an `if` statement for each optional query parameter, resulting in a large number of possible branches through the code.
Since `cyclomatic_complexity` is configured as an error, generated code may be blocked from building until we manually add `swiftlint:disable` comments to selectively turn it off.
I have yet to see a situation in our code where the `cyclomatic_complexity` error is …
=> Disable cyclomatic complexity style check

Source/PersonalityInsightsV3/Models/Behavior.swift, Source/PersonalityInsightsV3/Models/ConsumptionPreferences.swift, Source/PersonalityInsightsV3/Models/ConsumptionPreferencesCategory.swift, Source/PersonalityInsightsV3/Models/Content.swift, Source/PersonalityInsightsV3/Models/ContentItem.swift, Source/PersonalityInsightsV3/Models/Profile.swift, Source/PersonalityInsightsV3/Models/Trait.swift, Source/PersonalityInsightsV3/Models/Warning.swift, Source/PersonalityInsightsV3/PersonalityInsights.swift
In addition to updating Personality Insights to conform to the latest style produced by the generator, this pull request changes the order of the `consumptionPreferences` and `csvHeaders` parameters.
Unfortunately, those parameters were swapped with this [commit][1] to the API definition. It's a backwards-incompatible change for Swift (and possibly other languages).
[1]: https://github.ibm.com/Watson/developer-cloud--api-definitions/commit/2adb55dca35609452e3288800c7f316544d07c6c#diff-6e067731bbc6e1a453f51152d65e1823L115
=> Regenerate Personality Insights

Source/LanguageTranslatorV2/LanguageTranslator.swift
After #800 is merged, this pull request will reorder the Language Translator service according to the API definition.
The following command is a handy way to verify that this is only a reordering of the methods:
`bash -c 'diff <(sort Service-Before.swift) <(sort Service-After.swift)'`
=> Reorder Language Translator According to API Definition

Source/NaturalLanguageUnderstandingV1/NaturalLanguageUnderstanding.swift
After #801 is merged, this pull request will reorder the Natural Language Understanding service according to the API definition.
The following command is a handy way to verify that this is only a reordering of the methods:
`bash -c 'diff <(sort Service-Before.swift) <(sort Service-After.swift)'`
=> Reorder Natural Language Understanding According to the API Definition

Source/TextToSpeechV1/TextToSpeech.swift
After #804 is merged, this pull request will reorder the Text to Speech service according to the API definition.
The following command is a handy way to verify that this is only a reordering of the methods:
`bash -c 'diff <(sort Service-Before.swift) <(sort Service-After.swift)'`
=> Reorder Text to Speech According to API Definition

Tests/VisualRecognitionV3Tests/VisualRecognitionTests.swift, WatsonDeveloperCloud.xcodeproj/project.pbxproj, WatsonDeveloperCloud.xcodeproj/xcshareddata/xcschemes/VisualRecognitionV3.xcscheme
This PR disables all tests (some were already disabled) that create or delete classifiers.  This will hurt coverage statistics, but should improve reliability / performance of the VR tests by avoiding "ghost classifiers" that can occur when classifiers are deleted before being fully available.
I've also deleted a tearDown function that deleted orphaned classifiers, again to avoid unreclaimed resources and to generally speed up the tests.
Note that the disabled tests can still be run "by hand" in Xcode -- and should -- to verify correct behavior of the create & delete paths.
=> Changes to VR tests to improve reliability

Source/RestKit/RestRequest.swift, Source/VisualRecognitionV3/VisualRecognition+CoreML.swift
Updated RestRequest.init to remove params, in relation to this issue: https://github.ibm.com/arf/planning-sdk-squad/issues/496
=> Updated RestRequest.init to remove params

Scripts/coverage.sh, Scripts/upload-coverage.sh
This PR adds two scripts to collect and upload coverage information.  These scripts are not run as part of the regular CI/CD flow because coverage collection is still a bit unreliable.  The intent is to run these scripts manually to report coverage for each new release.
Coverage reports are uploaded to codecov.io.  I used these scripts to collect and report coverage for the most recent release, v0.26.0.  You can see the latest report here:
https://codecov.io/gh/watson-developer-cloud/swift-sdk
=> Add scripts to collect coverage info and upload coverage report

Scripts/run-tests.sh, Tests/SpeechToTextV1Tests/SpeechToTextTests.swift, WatsonDeveloperCloud.xcodeproj/xcshareddata/xcschemes/LanguageTranslatorV3.xcscheme
The run-tests.sh script was reporting a non-zero exit code even when there were no test failures.  This problem did not occur when testing locally.  It turned out that the problem was that the scheme for LanguageTranslatorV3 was not added to the project.
This PR adds the LTv3 scheme and includes a few other minor fixes to improve test reliability.
=> Fix run-tests to report success when all tests pass

Source/RestKit/RestError.swift, Source/RestKit/RestRequest.swift, Tests/AssistantV1Tests/AssistantTests.swift
This PR replaces force unwraps with guard statements when constructing the URL for a request.  The force unwraps will cause an app crash if the URL is malformed, which could happen if the user provided an incorrect value for the serviceURL.  The new logic will call the `failure` completion handler with a `badURL` error.
=> Handle malformed URLs when constructing URL requests

Source/AssistantV1/RestKit/WatsonResponse.swift, Source/ConversationV1/RestKit/WatsonResponse.swift, Source/DiscoveryV1/RestKit/WatsonResponse.swift, Source/LanguageTranslatorV2/RestKit/WatsonResponse.swift, Source/LanguageTranslatorV3/RestKit/WatsonResponse.swift, Source/NaturalLanguageClassifierV1/RestKit/WatsonResponse.swift, Source/NaturalLanguageUnderstandingV1/RestKit/WatsonResponse.swift, Source/PersonalityInsightsV3/RestKit/WatsonResponse.swift, Source/RestKit/Authentication.swift, Source/RestKit/RestRequest.swift, Source/RestKit/WatsonResponse.swift, Source/SpeechToTextV1/RestKit/WatsonResponse.swift, Source/TextToSpeechV1/RestKit/WatsonResponse.swift, Source/ToneAnalyzerV3/RestKit/WatsonResponse.swift, Source/ToneAnalyzerV3/ToneAnalyzer.swift, Source/VisualRecognitionV3/RestKit/WatsonResponse.swift, Tests/ToneAnalyzerV3Tests/ToneAnalyzerTests.swift, WatsonDeveloperCloud.xcodeproj/project.pbxproj
This PR contains the RestKit changes to support service methods with a single completion handler.
The single completion handler is more consistent with the style of Apple APIs.
The signature for the completion handler is:
```
(WatsonResponse<T>?, Error?) -> Void
```
The `WatsonResponse` is a new `struct` (class) that contains the service response code, the method result (a `T`), and a `headers` dictionary containing response headers.
This PR includes a generated ToneAnalyzer service with updated tests to use the single completion handler.  This shows some concrete examples of the new API design.
The other services have not been regenerated or updated, so these will fail to build -- that is expected.
=> Single completion handler

Source/VisualRecognitionV3/VisualRecognition+CoreML.swift, Source/VisualRecognitionV3/VisualRecognition+UIImage.swift, Tests/VisualRecognitionV3Tests/VisualRecognition+CoreMLTests.swift, Tests/VisualRecognitionV3Tests/VisualRecognition+UIImageTests.swift
This PR changes the `classifyWithLocalModel` method of VisualRecognition+CoreML to take an imagesFile of type URL rather than an image of type UIImage.  This change fixes a build problem for this file on macOS -- which isn't technically supported but is explicitly allowed by the ifdef enclosing the file.
The PR also adds a method to VisualRecognition+UIImage that conforms to the original `classifyWithLocalModel` signature, for backward-compatiblity.  The new method simply wraps the CoreML method in a manner similar to the other methods in this file.
=> Change VR classifyWithLocalModel to accept an imageFile

Source/DiscoveryV1/Discovery.swift
This PR fixes the `baseName` of `return` parameter, which was incorrectly set to the parameter "alternate name" by a generator bug.
The generator bug has been fixed, but I've patched this by hand this time around so that we don't have to wait for the next regen to get this corrected.
=> Manual fix for generator bug in shared params with alternate name

Source/RestKit/RestRequest.swift, Source/RestKit/WatsonResponse.swift, Source/SpeechToTextV1/SpeechToText+Recognize.swift, Tests/SpeechToTextV1Tests/SpeechToTextRecognizeTests.swift, Tests/SpeechToTextV1Tests/SpeechToTextTests.swift
This PR updates the Speech-to-Text tests for the new single completion handler design.
The PR also includes some minor changes/fixes in RestKit needed for STT.
Also included are updates to the hand-written Recognize extension to adopt the new single completion handler design.
=> Update Speech-to-Text tests for single completion handler

Tests/LanguageTranslatorV3Tests/LanguageTranslatorTests.swift
=> Update Language Translator V3 tests for single completion handler

Tests/DiscoveryV1Tests/DiscoveryTests.swift
=> Update Discovery tests for single completion handler 

Tests/NaturalLanguageClassifierV1Tests/NaturalLanguageClassifierTests.swift
=> Update NLC tests for single completion handler 

Source/PersonalityInsightsV3/PersonalityInsights.swift, Tests/PersonalityInsightsV3Tests/PersonalityInsightsTests.swift
This framework had somehow gotten out of sync with the API definitions, so I made the following changes in addition to the single completion handler updates:
1. `request.responseObject()` --> `request.response()`
1. Changed the `content` parameter in `PersonalityInsights.profile(content:)` from `String` --> `ProfileContent`
=> Update Personality Insights tests for single completion handler

Tests/AssistantV1Tests/AssistantTests.swift, Tests/ConversationV1Tests/ConversationTests.swift, Tests/DiscoveryV1Tests/DiscoveryTests.swift, Tests/LanguageTranslatorV3Tests/LanguageTranslatorTests.swift, Tests/NaturalLanguageClassifierV1Tests/NaturalLanguageClassifierTests.swift, Tests/NaturalLanguageUnderstandingV1Tests/NaturalLanguageUnderstandingV1Tests.swift, Tests/PersonalityInsightsV3Tests/PersonalityInsightsTests.swift, Tests/SpeechToTextV1Tests/SpeechToTextRecognizeTests.swift, Tests/SpeechToTextV1Tests/SpeechToTextTests.swift, Tests/TestUtilities.swift, Tests/TextToSpeechV1Tests/TextToSpeechPlaybackTests.swift, Tests/TextToSpeechV1Tests/TextToSpeechTests.swift, Tests/ToneAnalyzerV3Tests/ToneAnalyzerTests.swift, Tests/VisualRecognitionV3Tests/VisualRecognition+CoreMLTests.swift, Tests/VisualRecognitionV3Tests/VisualRecognition+UIImageTests.swift, Tests/VisualRecognitionV3Tests/VisualRecognitionTests.swift, Tests/VisualRecognitionV3Tests/VisualRecognitionWithIAMTests.swift, WatsonDeveloperCloud.xcodeproj/project.pbxproj
The main purpose of these changes is to take common XCTFail() messages and turn them into reusable constants or functions. I created a new file called `TestUtilities.swift` that we can use to hold code that is shared across multiple test suites. `Discovery`, `STT`, and `TTS` also have some failure messages unique to their tests.
I also made updates to the `Assistant` and `Tone Analyzer` tests for the new strategy we're using to decide how and when to fail tests (checking for an error, checking for `response?.result`, etc).
=> Unit tests refactoring

Source/SpeechToTextV1/SpeechToText+Recognize.swift, Source/SpeechToTextV1/WebSockets/RecognitionSettings.swift, Source/SpeechToTextV1/WebSockets/SpeechToTextSession.swift, Source/SpeechToTextV1/WebSockets/SpeechToTextSocket.swift, Tests/SpeechToTextV1Tests/SpeechToTextRecognizeTests.swift
This PR adds support for acoustic customizations to the STT `recognizeUsingWebSocket` method.
I've also added a `headers` parameter to this method to allow custom headers to be applied to the recognize operation, fixed some warning messages for use of deprecated methods, and added a test for recognize using a custom language model.
=> Add support for acoustic customizations to STT recognizeUsingWebSocket

Tests/VisualRecognitionV3Tests/VisualRecognitionWithIAMTests.swift, WatsonDeveloperCloud.xcodeproj/project.pbxproj
This PR fixes the copyright in `VisualRecognitionWithIAMTests` and updates the "Organization Name" for the project so that new files get a proper copyright inserted by Xcode.
=> Fix copyrights

Source/VisualRecognitionV3/VisualRecognition.swift, Tests/VisualRecognitionV3Tests/VisualRecognitionTests.swift
This PR fixes the VR getCoreMlModel method to correctly handle the response data as a byte stream (the model) rather than a JSON object.  A test was included to recreate the original problem and also verify the fix.
The change to getCoreMlModel is new hand edit that must be done as part of the post generation changes. I've updated the Wiki to include this so that it doesn't get lost in future releases.
This was my first experience using `git cz`.  Hopefully I did it right but please check and let me know if changes are needed.
=> Fix deserialization error in getCoreMlModel

.releaserc
Used the wrong name for the .zip file.
=> Fix uploading of prebuilt frameworks to Github release

Scripts/release-to-cocoapods.sh
The automated Cocoapods deployment failed on SpeechToTextV1, so the remaining pods need to be
published. The pods already published must be commented out to prevent failing the Travis script and
skipping the remaining deployments.
=> Temporarily comment out some services from Cocoapods deployment

Cartfile.resolved, Source/AssistantV1/Assistant.swift, Source/AssistantV2/Assistant.swift, Source/ConversationV1/Conversation.swift, Source/DiscoveryV1/Discovery.swift, Source/LanguageTranslatorV3/LanguageTranslator.swift, Source/NaturalLanguageClassifierV1/NaturalLanguageClassifier.swift, Source/NaturalLanguageUnderstandingV1/NaturalLanguageUnderstanding.swift, Source/PersonalityInsightsV3/PersonalityInsights.swift, Source/SpeechToTextV1/SpeechToText+Recognize.swift, Source/SpeechToTextV1/SpeechToText.swift, Source/SpeechToTextV1/WebSockets/SpeechToTextSession.swift, Source/SpeechToTextV1/WebSockets/SpeechToTextSocket.swift, Source/SupportingFiles/Shared.swift, Source/TextToSpeechV1/TextToSpeech.swift, Source/ToneAnalyzerV3/ToneAnalyzer.swift, Source/VisualRecognitionV3/VisualRecognition+CoreML.swift, Source/VisualRecognitionV3/VisualRecognition+UIImage.swift, Source/VisualRecognitionV3/VisualRecognition.swift, Tests/AssistantV1Tests/AssistantTests.swift, Tests/VisualRecognitionV3Tests/VisualRecognitionTests.swift
Resolves https://github.ibm.com/arf/planning-sdk-squad/issues/549
This takes the updates made to RestKit's `RestError` done in [this PR](https://github.com/watson-developer-cloud/restkit/pull/6), and applies them to the Swift SDK.
There are 3 main changes: 
1. The `errorResponseDecoder()` method on each service returns a `RestError.http` instead of an `NSError. The same was done in LanguageTranslator's `identify()` method.
1. Changed `RestError.encodingError` to `RestError.encoding(path: path)`, which specifies the URL path that failed to be encoded.
1. Changed `RestError.serializationError` to `RestError.serialization(values: "...")`, where `values` is some plain text that explains what values could not be serialized (usually the request body).
The corresponding generator changes are …
=> Error handling

Source/VisualRecognitionV3/VisualRecognition+CoreML.swift
validate compiler version to ensure `MLModelConfiguration` is available
compiler check logic based on this proposal:
https://github.com/apple/swift-evolution/blob/master/proposals/0212-compiler-version-directive.md
=> temporary workaround for new A12 based devices - v2

Source/SpeechToTextV1/SpeechToText+Recognize.swift
Fixes https://github.com/watson-developer-cloud/swift-sdk/issues/916
SpeechToText `recognizeMicrophone()` was only working if the SpeechToText instance was instantiated using basic auth. This fix allows the method to work with any supported authentication method.
=> Fix SpeechToText recognizeMicrophone()

.travis.yml, Source/SpeechToTextV1/SpeechToText+Recognize.swift
- Fixes https://github.com/watson-developer-cloud/swift-sdk/issues/916
- Removes Cocoapods and API docs publishing from the release build on Travis. Those steps were causing the Travis build to fail due to reaching the 50 minute timeout. Those steps will need to be done manually.
=> Release 0.38.1

Source/SpeechToTextV1/SpeechToText.swift, Tests/SpeechToTextV1Tests/SpeechToTextRecognizeTests.swift, Tests/SpeechToTextV1Tests/SpeechToTextUnitTests.swift, WatsonDeveloperCloud.xcodeproj/project.pbxproj
https://github.ibm.com/arf/planning-sdk-squad/issues/749
SpeechToText `tokenURL` and `websocketURL` are changed from `public` to `internal`. When the `serviceURL` gets set, the `tokenURL` and `websocketURL` are also set depending on the value of `serviceURL`.
=> STT tokenURL and websocketURL

Source/SpeechToTextV1/SpeechToText+Recognize.swift, Source/SpeechToTextV1/WebSockets/RecognitionSettings.swift, Source/SpeechToTextV1/WebSockets/SpeechToTextSession.swift, Source/SpeechToTextV1/WebSockets/SpeechToTextSocket.swift, Tests/SpeechToTextV1Tests/SpeechToTextRecognizeTests.swift, Tests/SpeechToTextV1Tests/SpeechToTextUnitTests.swift
https://github.ibm.com/arf/planning-sdk-squad/issues/761
Adds parameters that the `SpeechToTextSession` class was missing. The parameters were taken from the [API docs](https://console.test.cloud.ibm.com/apidocs/speech-to-text#websocket_methods). `customizationID` was removed since it is deprecated in favor of `languageCustomizationID`.
=> Add missing parameters to SpeechToTextSession

.travis.yml, Scripts/run-tests.sh, Scripts/travis/deploy-to-cocoapods.sh, Scripts/travis/new-release.sh, Scripts/travis/publish-documentation.sh, Scripts/travis/test-Linux.sh, Scripts/travis/test-macOS.sh
https://github.ibm.com/arf/planning-sdk-squad/issues/751
Travis builds were timing out during deployment of new versions. This PR splits up the Travis build into 5 jobs. Rather than a single 50 minute timeout for all of the steps, each individual step gets its own 50 minute time allocation. The steps are as follows, and are run serially:
1. Run tests on Linux (currently commented out)
1. Run tests on macOS (currently commented out)
1. Run semantic-release
1. Deploy to Cocoapods
1. Generate and publish new API docs
=> Fix travis timeouts

.travis.yml
This is done as a very temporary measure to quickly release an emergency fix. I already verified that the test scripts succeed. I will revert this later.
=> Temporarily disable tests on Travis for master branch

Source/AssistantV1/Assistant.swift, Source/AssistantV2/Assistant.swift, Source/CompareComplyV1/CompareComply.swift, Source/DiscoveryV1/Discovery.swift, Source/LanguageTranslatorV3/LanguageTranslator.swift, Source/NaturalLanguageClassifierV1/NaturalLanguageClassifier.swift, Source/NaturalLanguageUnderstandingV1/NaturalLanguageUnderstanding.swift, Source/PersonalityInsightsV3/PersonalityInsights.swift, Source/SpeechToTextV1/SpeechToText+Recognize.swift, Source/SpeechToTextV1/SpeechToText.swift, Source/SupportingFiles/Shared.swift, Source/SupportingFiles/SharedTests.swift, Source/TextToSpeechV1/TextToSpeech.swift, Source/ToneAnalyzerV3/ToneAnalyzer.swift, Source/VisualRecognitionV3/VisualRecognition.swift
https://github.ibm.com/Watson/developer-experience/issues/6057
Adds the following 2 headers to every request:
1) User-Agent
2) X-IBMCloud-SDK-Analytics
The `User-Agent` header was already being added through RestKit, but I refactored how it gets generated and added (same way as the new `X-IBMCloud-SDK-Analytics` header)
=> Add metadata headers

README.md, Source/AssistantV1/Assistant.swift, Source/AssistantV2/Assistant.swift, Source/CompareComplyV1/CompareComply.swift, Source/DiscoveryV1/Discovery.swift, Source/LanguageTranslatorV3/LanguageTranslator.swift, Source/NaturalLanguageClassifierV1/NaturalLanguageClassifier.swift, Source/NaturalLanguageUnderstandingV1/NaturalLanguageUnderstanding.swift, Source/PersonalityInsightsV3/PersonalityInsights.swift, Source/SpeechToTextV1/SpeechToText.swift, Source/SupportingFiles/Shared.swift, Source/SupportingFiles/SharedTests.swift, Source/SupportingFiles/ibm-credentials.env, Source/TextToSpeechV1/TextToSpeech.swift, Source/ToneAnalyzerV3/ToneAnalyzer.swift, Source/VisualRecognitionV3/VisualRecognition.swift, WatsonDeveloperCloud.xcodeproj/project.pbxproj
https://github.ibm.com/Watson/developer-experience/issues/5982
For Swift, I decided it makes the most sense to have one new initializer for each service that accepts a `URL` which points to the credentials file. For iOS apps, there is no reliable way to be able to find a file that exists within the app, from a separate framework (the Watson SDK).
Most of the logic is in the Shared.swift file. Please let me know if there are corner cases you think I should add to my tests.
=> Support loading credentials from file

Source/SpeechToTextV1/SpeechToText+Recognize.swift, Source/SpeechToTextV1/WebSockets/RecognizeCallback.swift, Tests/SpeechToTextV1Tests/SpeechToTextRecognizeTests.swift, WatsonDeveloperCloud.xcodeproj/project.pbxproj
The PR changes the interface to the websockets methods of STT to return results to the user with the standard `onResults` and `onError` callback methods, rather than `completionHandler`. This gives the methods a more natural "websockety" design as well as simplifies the implementation.
Due to issues with ARC reclamation of the STT session object, I was not able to implement `onDisconnect` reliably, so I simply left out the `onConnect` and `onDisconnect` callbacks normally present in websocket interfaces. Since these callbacks weren't supported previously, this is no loss of functionality, and I believe we could add them later in a compatible fashion.
=> Rework STT websockets methods

IBMWatsonAssistantV1.podspec, IBMWatsonAssistantV2.podspec, IBMWatsonCompareComplyV1.podspec, IBMWatsonDiscoveryV1.podspec, IBMWatsonLanguageTranslatorV3.podspec, IBMWatsonNaturalLanguageClassifierV1.podspec, IBMWatsonNaturalLanguageUnderstandingV1.podspec, IBMWatsonPersonalityInsightsV3.podspec, IBMWatsonSpeechToTextV1.podspec, IBMWatsonTextToSpeechV1.podspec, IBMWatsonToneAnalyzerV3.podspec, IBMWatsonVisualRecognitionV3.podspec, README.md, Source/AssistantV1/Assistant.swift, Source/AssistantV2/Assistant.swift, Source/CompareComplyV1/CompareComply.swift, Source/DiscoveryV1/Discovery.swift, Source/LanguageTranslatorV3/LanguageTranslator.swift, Source/NaturalLanguageClassifierV1/NaturalLanguageClassifier.swift, Source/NaturalLanguageUnderstandingV1/NaturalLanguageUnderstanding.swift, Source/PersonalityInsightsV3/PersonalityInsights.swift, Source/SpeechToTextV1/SpeechToText.swift, Source/SupportingFiles/InsecureConnection.swift, Source/TextToSpeechV1/TextToSpeech.swift, Source/ToneAnalyzerV3/ToneAnalyzer.swift, Source/VisualRecognitionV3/VisualRecognition.swift, Tests/AssistantV1Tests/AssistantV1UnitTests.swift, WatsonDeveloperCloud.xcodeproj/project.pbxproj
This PR adds the `disableSSLVerification` method to each service that allows network requests to a server without verification of the server certificate.  This support is needed for some ICP deployments.
=> Add support for insecure connections

.travis.yml, Scripts/travis/publish-documentation.sh
we have recently enabled running PR builds to test PRs against the master branch. 
However, there is some undesired behavior with travis using the Jobs conditional syntax where `branch = master` is True on a PR (since they run on the base branch). This change makes it so that we only run the
deploy stages if we are actually pushing to the master branch (after a PR has been merged).
=> ci(travis): require master branch stages to be a non-PR non-fork

.travis.yml, IBMWatsonAssistantV1.podspec, IBMWatsonAssistantV2.podspec, IBMWatsonCompareComplyV1.podspec, IBMWatsonDiscoveryV1.podspec, IBMWatsonDiscoveryV2.podspec, IBMWatsonLanguageTranslatorV3.podspec, IBMWatsonNaturalLanguageClassifierV1.podspec, IBMWatsonNaturalLanguageUnderstandingV1.podspec, IBMWatsonPersonalityInsightsV3.podspec, IBMWatsonSpeechToTextV1.podspec, IBMWatsonTextToSpeechV1.podspec, IBMWatsonToneAnalyzerV3.podspec, IBMWatsonVisualRecognitionV3.podspec, IBMWatsonVisualRecognitionV4.podspec
We now use `v{Version}` prefix for Git tags, so we need to update the podspecs to match.
=> build(cocoapods): use v-prefixed version

IBMWatsonSpeechToTextV1.podspec, IBMWatsonTextToSpeechV1.podspec
We do not support the XCFramework solution for Apple Silicon at this time, so we need to exclude
arm64 from the build architectures for STT and TTS.,
=> fix(cocoapods): exclude arm64 architecture from cocoapods builds
