watson-developer-cloud/swift-sdk

WatsonDeveloperCloud.xcodeproj/xcshareddata/xcschemes/All Services.xcscheme

This PR adds an "All Services" shared scheme, which makes it easier for developers to build and test all services at once.

Add "All Services" scheme to RestKit branch

---

Package.swift

- Change name from `ios-sdk` to `WatsonDeveloperCloud`
- Add targets for each service
Related Issues:
- #120

[dev-ops] update Package.swift

---

Source/AlchemyVisionV1/AlchemyVision.swift
Source/DialogV1/Dialog.swift
Source/LanguageTranslationV2/LanguageTranslation.swift
Source/NaturalLanguageClassifierV1/NaturalLanguageClassifier.swift
Source/PersonalityInsightsV2/PersonalityInsights.swift
Source/SpeechToTextV1/SpeechToText.swift
Source/SpeechToTextV1/SpeechToTextAudioStreamer.swift
Source/SpeechToTextV1/SpeechToTextWebSocket.swift
Source/TextToSpeechV1/TextToSpeech.swift
Source/ToneAnalyzerV3/ToneAnalyzer.swift
Source/VisualRecognitionV3/VisualRecognition.swift

Add serviceURL as an argument to all service initializers

---

Source/AlchemyLanguageV1/Utils/NetworkUtils.swift
Source/AlchemyVisionV1/AlchemyVision.swift
Source/DialogV1/Dialog.swift
Source/LanguageTranslationV2/LanguageTranslation.swift
Source/NaturalLanguageClassifierV1/NaturalLanguageClassifier.swift
Source/PersonalityInsightsV2/PersonalityInsights.swift
Source/RestKit/RestRequest.swift
Source/RestKit/RestUtilities.swift
Source/SpeechToTextV1/SpeechToTextAudioStreamer.swift
Source/SpeechToTextV1/SpeechToTextWebSocket.swift
Source/TextToSpeechV1/TextToSpeech.swift
Source/ToneAnalyzerV3/ToneAnalyzer.swift
Source/VisualRecognitionV3/VisualRecognition.swift
WatsonDeveloperCloud.xcodeproj/project.pbxproj

This pull request adds a user-agent header to all REST requests. This was partially completed in previous releases, but still needed to be implemented within the `rest-kit` architecture.
The user agent includes the following information:
`sdk-version/service-version executable/bundle (version; os)`

Add user agent header

---

Source/LanguageTranslationV2/LanguageTranslation.swift

Provide a general description of the code changes in your pull
request... were there any bugs you had fixed? If so, mention them. If
these bugs have open GitHub issues, be sure to tag them here as well,
to keep the conversation linked together.
If there's anything else that's important and relevant to your pull
request, mention that information here.

Update Language Translation documentation

---

Source/ToneAnalyzerV3/Tests/ToneAnalyzerTests.swift

This pull request updates ToneAnalyzer tests to have better verification as requested by #267

Update ToneAnalyzer tests

---

README.md

The documentation of the Visual Recognition was a copy-paster-version of the Tone Analyzer Service and didn't make sense. I've added some simple text to explain the service and how to use f.e. Face Detection. All in all, nothing special ✌️

Add documentation for Visual Recognition

---

Source/AlchemyLanguageV1/AlchemyLanguageV1.swift
Source/AlchemyLanguageV1/Tests/AlchemyLanguageV1Tests.swift

As discussed in issue #319 here are some changes of the AlchemyLanguage API to make it clearer for developers.
Furthermore I will open a separate branch to discuss more refactoring for an easier understanding API.

Clean alchemy language api

---

Source/AlchemyDataNewsV1/Models/DocumentSource.swift
Source/AlchemyDataNewsV1/Models/Entity.swift
Source/AlchemyDataNewsV1/Models/NewsResponse.swift
Source/AlchemyLanguageV1/AlchemyLanguage.swift
Source/AlchemyLanguageV1/Models/DocumentEmotion.swift
Source/AlchemyLanguageV1/Models/Entity.swift
Source/AlchemyLanguageV1/Models/Language.swift
Source/AlchemyLanguageV1/Models/QueryParam.swift
Source/AlchemyLanguageV1/Models/SAORelation.swift
Source/DocumentConversionV1/DocumentConversion.swift
Source/DocumentConversionV1/Models/FileType.swift
Source/RelationshipExtractionV1Beta/Models/Relations.swift
Source/TextToSpeechV1/Models/SynthesisVoice.swift

Update undocumented code

---

README.md
WatsonDeveloperCloud.xcodeproj/project.pbxproj

This pull request lowers the minimum supported version of iOS from 9.0 to 8.0.

Add support for iOS 8+

---

README.md
Source/ConversationV1/Conversation.swift
Source/ConversationV1/Models/Context.swift
Source/ConversationV1/Models/InputData.swift
Source/ConversationV1/Models/MessageRequest.swift
Source/ConversationV1/Models/MessageResponse.swift
Source/ConversationV1/Tests/ConversationTests.swift
Source/ConversationV1/Tests/car_workspace.json
Source/ConversationV1Experimental/Conversation.swift
Source/SupportingFiles/ConversationV1.h
WatsonDeveloperCloud.xcodeproj/project.pbxproj
WatsonDeveloperCloud.xcodeproj/xcshareddata/xcschemes/ConversationV1.xcscheme

This pull request adds the ConversationV1 service.
Note that the existing ConversationV1Experimental class remains unchanged. It should remain in the SDK until support is dropped for the experimental Conversation service.

Add ConversationV1 service

---

Documentation/Quickstart.md

Provide a general description of the code changes in your pull
request... were there any bugs you had fixed? If so, mention them. If
these bugs have open GitHub issues, be sure to tag them here as well,
to keep the conversation linked together.
If there's anything else that's important and relevant to your pull
request, mention that information here.
Adding additional step which I have missed a couple times when following this quick start guide ;)

Quick clarification of framework copying

---

Source/VisualRecognitionV3/Tests/VisualRecognitionTests.swift
Source/VisualRecognitionV3/VisualRecognition.swift

Add functionality to Visual Recognition to update a classifier

---

Source/DialogV1/Dialog.swift

Add deprecation annotation to Dialog

---

Source/SpeechToTextV1/Models/TranscriptionSettings.swift
Source/TextToSpeechV1/Tests/TextToSpeechTests.swift

This pull request adds a TextToSpeech test for Japanese text and updates a broken link in the SpeechToText TranscriptionSettings.

Fix speech bugs

---

Cartfile
Cartfile.resolved
README.md
Source/DialogV1/Dialog.swift
Source/DocumentConversionV1/DocumentConversion.swift
Source/RetrieveAndRankV1/RetrieveAndRank.swift
Source/VisualRecognitionV3/VisualRecognition.swift
WatsonDeveloperCloud.xcodeproj/project.pbxproj
WatsonDeveloperCloud.xcodeproj/xcshareddata/xcschemes/AlchemyDataNewsV1.xcscheme
WatsonDeveloperCloud.xcodeproj/xcshareddata/xcschemes/AlchemyLanguageV1.xcscheme
WatsonDeveloperCloud.xcodeproj/xcshareddata/xcschemes/AlchemyVisionV1.xcscheme
WatsonDeveloperCloud.xcodeproj/xcshareddata/xcschemes/ConversationV1.xcscheme
WatsonDeveloperCloud.xcodeproj/xcshareddata/xcschemes/ConversationV1Experimental.xcscheme
WatsonDeveloperCloud.xcodeproj/xcshareddata/xcschemes/DialogV1.xcscheme
WatsonDeveloperCloud.xcodeproj/xcshareddata/xcschemes/DocumentConversionV1.xcscheme
WatsonDeveloperCloud.xcodeproj/xcshareddata/xcschemes/LanguageTranslatorV2.xcscheme
WatsonDeveloperCloud.xcodeproj/xcshareddata/xcschemes/NaturalLanguageClassifierV1.xcscheme
WatsonDeveloperCloud.xcodeproj/xcshareddata/xcschemes/PersonalityInsightsV2.xcscheme
WatsonDeveloperCloud.xcodeproj/xcshareddata/xcschemes/RelationshipExtractionV1Beta.xcscheme
WatsonDeveloperCloud.xcodeproj/xcshareddata/xcschemes/RestKit.xcscheme
WatsonDeveloperCloud.xcodeproj/xcshareddata/xcschemes/RetrieveAndRankV1.xcscheme
WatsonDeveloperCloud.xcodeproj/xcshareddata/xcschemes/SpeechToTextV1.xcscheme
WatsonDeveloperCloud.xcodeproj/xcshareddata/xcschemes/TextToSpeechV1.xcscheme
WatsonDeveloperCloud.xcodeproj/xcshareddata/xcschemes/ToneAnalyzerV3.xcscheme
WatsonDeveloperCloud.xcodeproj/xcshareddata/xcschemes/TradeoffAnalyticsV1.xcscheme
WatsonDeveloperCloud.xcodeproj/xcshareddata/xcschemes/VisualRecognitionV3.xcscheme

This pull request updates the SDK to Swift 2.3. Builds were executed in Xcode 8 GM. Tests pass except for some server-related errors.

Update to Swift 2.3

---

Source/AlchemyDataNewsV1/AlchemyDataNews.swift
Source/AlchemyLanguageV1/AlchemyLanguage.swift
Source/AlchemyVisionV1/AlchemyVision.swift
Source/ConversationV1/Conversation.swift
Source/ConversationV1Experimental/Conversation.swift
Source/DialogV1/Dialog.swift
Source/DocumentConversionV1/DocumentConversion.swift
Source/LanguageTranslatorV2/LanguageTranslator.swift
Source/NaturalLanguageClassifierV1/NaturalLanguageClassifier.swift
Source/PersonalityInsightsV2/PersonalityInsights.swift
Source/RelationshipExtractionV1Beta/RelationshipExtraction.swift
Source/RetrieveAndRankV1/RetrieveAndRank.swift
Source/SpeechToTextV1/SpeechToText.swift
Source/SpeechToTextV1/SpeechToTextSession.swift
Source/SpeechToTextV1/SpeechToTextSocket.swift
Source/TextToSpeechV1/TextToSpeech.swift
Source/ToneAnalyzerV3/ToneAnalyzer.swift
Source/TradeoffAnalyticsV1/TradeoffAnalytics.swift
Source/VisualRecognitionV3/VisualRecognition.swift

This pull request changes the service URLs to public properties, addressing issue #438.

Update service urls

---

Source/AlchemyDataNewsV1/AlchemyDataNews.swift
Source/AlchemyLanguageV1/AlchemyLanguage.swift
Source/AlchemyVisionV1/AlchemyVision.swift
Source/ConversationV1/Conversation.swift
Source/ConversationV1Experimental/Conversation.swift
Source/DialogV1/Dialog.swift
Source/DocumentConversionV1/DocumentConversion.swift
Source/LanguageTranslatorV2/LanguageTranslator.swift
Source/NaturalLanguageClassifierV1/NaturalLanguageClassifier.swift
Source/PersonalityInsightsV2/PersonalityInsights.swift
Source/RelationshipExtractionV1Beta/RelationshipExtraction.swift
Source/RestKit/RestRequest.swift
Source/RetrieveAndRankV1/RetrieveAndRank.swift
Source/SpeechToTextV1/SpeechToText.swift
Source/SpeechToTextV1/SpeechToTextSession.swift
Source/SpeechToTextV1/SpeechToTextSocket.swift
Source/TextToSpeechV1/TextToSpeech.swift
Source/ToneAnalyzerV3/ToneAnalyzer.swift
Source/TradeoffAnalyticsV1/TradeoffAnalytics.swift
Source/VisualRecognitionV3/VisualRecognition.swift

This pull request enables users to set the default HTTP headers to use for all requests with any service. (In particular, it makes it easy to specify the `X-Watson-Learning-Opt-Out` header for any service.)
Closes #360

Add support for setting default headers (#360)

---

Source/AlchemyDataNewsV1/AlchemyDataNews.swift
Source/AlchemyDataNewsV1/Tests/AlchemyDataNewsTests.swift

Renamed method and updated corresponding tests

Updated AlchemyDataNews per Swift 3.0 naming conventions

---

Source/RelationshipExtractionV1Beta/Models/Entity.swift
Source/RelationshipExtractionV1Beta/Models/Mention.swift
Source/RelationshipExtractionV1Beta/Models/Relations.swift
Source/RelationshipExtractionV1Beta/RelationshipExtraction.swift
Source/RelationshipExtractionV1Beta/Tests/RelationshipExtractionTests.swift

Updated enums, parameter names for the `getRelationships` method, and tests

Updated Relationship Extraction

---

Source/AlchemyLanguageV1/AlchemyLanguage.swift
Source/AlchemyLanguageV1/Models/QueryParam.swift
Source/AlchemyLanguageV1/Tests/AlchemyLanguageTests.swift

Renamed methods and updated tests

Updated Alchemy Language

---

Source/ConversationV1/Conversation.swift
Source/ConversationV1/Tests/ConversationTests.swift

Updated method and corresponding tests

Updated Conversation method

---

Source/AlchemyVisionV1/AlchemyVision.swift
Source/AlchemyVisionV1/Tests/AlchemyVisionTests.swift

Updated methods and corresponding tests

Updated methods in Alchemy Vision

---

Source/PersonalityInsightsV2/PersonalityInsights.swift
Source/PersonalityInsightsV2/Tests/PersonalityInsightsTests.swift

Updated parameter names and tests

Updated Personality Insights per Swift 3.0 naming

---

Source/DocumentConversionV1/DocumentConversion.swift
Source/DocumentConversionV1/DocumentConversionV1Tests/DocumentConversionTests.swift
Source/DocumentConversionV1/Models/FileType.swift

Updated parameter names, enums, and tests

Updated naming for DocumentConversion

---

Source/NaturalLanguageClassifierV1/Models/ClassifierDetails.swift
Source/NaturalLanguageClassifierV1/NaturalLanguageClassifier.swift
Source/NaturalLanguageClassifierV1/Tests/NaturalLanguageClassifierTests.swift

Updated method names, enum names, and tests

Updated NLC according to Swift 3.0 naming conventions

---

README.md

Wrote a quick summary with some code snippets about how to set the service URL and custom headers. Let me know if it could be longer/more descriptive!
Wasn't sure where to locate it in the README, so I put it right after the section we talk about service instances.

Updating documentation about custom service URLs and headers

---

Source/SpeechToTextV1/SpeechToText.swift
Tests/SpeechToTextV1Tests/SpeechToTextTests.swift

Updated one of the methods to use the customizationID parameter. Added a test that transcribes an audio file using a trained custom model. Addresses issue #518.

Speech to Text Customization

---

Source/VisualRecognitionV3/Models/CollectionImages.swift
Source/VisualRecognitionV3/VisualRecognition.swift
Tests/VisualRecognitionV3Tests/VisualRecognitionTests.swift

Visual recognition

---

Source/RetrieveAndRankV1/RetrieveAndRank.swift
Tests/RetrieveAndRankV1Tests/RetrieveAndRankTests.swift

This would address issue #559.

Adding functionality to Retrieve and Rank to specify number of rows to return

---

Tests/LanguageTranslatorV2Tests/LanguageTranslatorTests.swift

Provide a general description of the code changes in your pull
request... were there any bugs you had fixed? If so, mention them. If
these bugs have open GitHub issues, be sure to tag them here as well,
to keep the conversation linked together.
If there's anything else that's important and relevant to your pull
request, mention that information here.

Fixed issue with Linux reading glossary

---

Source/RestKit/MultipartFormData.swift

Update to proper header information

Update to proper header information

---

README.md

Update example for Natural Language Understanding

Update Natural Language Understanding example in README.md

---

Source/NaturalLanguageUnderstandingV1/Models/Features.swift
Source/NaturalLanguageUnderstandingV1/Models/Parameters.swift
Source/NaturalLanguageUnderstandingV1/NaturalLanguageUnderstanding.swift
Tests/NaturalLanguageUnderstandingV1Tests/NaturalLanguageUnderstandingV1Tests.swift

Updated the serviceURL. Also updated some comments/tests to make it clear that at least one feature is required for the analyze request.

Updated NLU service

---

Source/SpeechToTextV1/Models/RecognitionSettings.swift
Source/SpeechToTextV1/Models/SpeakerLabel.swift
Source/SpeechToTextV1/Models/SpeechRecognitionEvent.swift
Source/SpeechToTextV1/Models/SpeechRecognitionResults.swift
Tests/SpeechToTextV1Tests/SpeechToTextTests.swift
WatsonDeveloperCloud.xcodeproj/project.pbxproj

Add code to support speaker labels for SpeechToTextV1.

Add speaker labels

---

.travis.yml

Updating the -sdk and -destination flags so that Travis will build properly.

Updating travis.yml

---

Source/ConversationV1/Conversation.swift
Source/ConversationV1/Models/CounterexampleCollectionResponse.swift
Source/ConversationV1/Models/CreateDialogNode.swift
Source/ConversationV1/Models/CreateEntity.swift
Source/ConversationV1/Models/CreateExample.swift
Source/ConversationV1/Models/CreateIntent.swift
Source/ConversationV1/Models/CreateValue.swift
Source/ConversationV1/Models/CreateWorkspace.swift
Source/ConversationV1/Models/EntityExportResponse.swift
Source/ConversationV1/Models/ExampleCollectionResponse.swift
Source/ConversationV1/Models/ExampleResponse.swift
Source/ConversationV1/Models/IntentCollectionResponse.swift
Source/ConversationV1/Models/IntentExportResponse.swift
Source/ConversationV1/Models/IntentResponse.swift
Source/ConversationV1/Models/PaginationResponse.swift
Source/ConversationV1/Models/UpdateExample.swift
Source/ConversationV1/Models/UpdateIntent.swift
Source/ConversationV1/Models/UpdateWorkspace.swift
Source/ConversationV1/Models/ValueExportResponse.swift
Source/ConversationV1/Models/WorkspaceCollectionResponse.swift
Source/ConversationV1/Models/WorkspaceExportResponse.swift
Source/ConversationV1/Models/WorkspaceResponse.swift
Tests/ConversationV1Tests/ConversationTests.swift
WatsonDeveloperCloud.xcodeproj/project.pbxproj

Add new APIs for Conversation V1, generated using SDK generator, and hand-written integration tests.

Generated models and APIs for new Conversation APIs

---

WatsonDeveloperCloud.xcodeproj/xcshareddata/xcschemes/AlchemyDataNewsV1.xcscheme
WatsonDeveloperCloud.xcodeproj/xcshareddata/xcschemes/AlchemyLanguageV1.xcscheme
WatsonDeveloperCloud.xcodeproj/xcshareddata/xcschemes/AlchemyVisionV1.xcscheme
WatsonDeveloperCloud.xcodeproj/xcshareddata/xcschemes/ConversationV1.xcscheme
WatsonDeveloperCloud.xcodeproj/xcshareddata/xcschemes/DialogV1.xcscheme
WatsonDeveloperCloud.xcodeproj/xcshareddata/xcschemes/DiscoveryV1.xcscheme
WatsonDeveloperCloud.xcodeproj/xcshareddata/xcschemes/DocumentConversionV1.xcscheme
WatsonDeveloperCloud.xcodeproj/xcshareddata/xcschemes/LanguageTranslatorV2.xcscheme
WatsonDeveloperCloud.xcodeproj/xcshareddata/xcschemes/NaturalLanguageClassifierV1.xcscheme
WatsonDeveloperCloud.xcodeproj/xcshareddata/xcschemes/NaturalLanguageUnderstandingV1.xcscheme
WatsonDeveloperCloud.xcodeproj/xcshareddata/xcschemes/PersonalityInsightsV2.xcscheme
WatsonDeveloperCloud.xcodeproj/xcshareddata/xcschemes/PersonalityInsightsV3.xcscheme
WatsonDeveloperCloud.xcodeproj/xcshareddata/xcschemes/RelationshipExtractionV1Beta.xcscheme
WatsonDeveloperCloud.xcodeproj/xcshareddata/xcschemes/RetrieveAndRankV1.xcscheme
WatsonDeveloperCloud.xcodeproj/xcshareddata/xcschemes/SpeechToTextV1.xcscheme
WatsonDeveloperCloud.xcodeproj/xcshareddata/xcschemes/TextToSpeechV1.xcscheme
WatsonDeveloperCloud.xcodeproj/xcshareddata/xcschemes/ToneAnalyzerV3.xcscheme
WatsonDeveloperCloud.xcodeproj/xcshareddata/xcschemes/TradeoffAnalyticsV1.xcscheme
WatsonDeveloperCloud.xcodeproj/xcshareddata/xcschemes/VisualRecognitionV3.xcscheme

Set the OS_ACTIVITY_MODE environment variable to `false` in all target schemes to suppress TCP debug messages, as recommended in the Apple Developer forum
https://forums.developer.apple.com/thread/49777

Suppress OS TCP messages in test output.

---

Source/RestKit/RestRequest.swift
Tests/DiscoveryV1Tests/DiscoveryTests.swift

Fix encoding for plus sign in query parameters.

---

Source/AlchemyDataNewsV1/AlchemyDataNews.swift
Source/AlchemyLanguageV1/AlchemyLanguage.swift
Source/AlchemyVisionV1/AlchemyVision.swift
Source/DialogV1/Dialog.swift
Source/DiscoveryV1/Discovery.swift
Source/DocumentConversionV1/DocumentConversion.swift
Source/LanguageTranslatorV2/LanguageTranslator.swift
Source/NaturalLanguageClassifierV1/NaturalLanguageClassifier.swift
Source/NaturalLanguageUnderstandingV1/NaturalLanguageUnderstanding.swift
Source/PersonalityInsightsV2/PersonalityInsights.swift
Source/PersonalityInsightsV3/PersonalityInsights.swift
Source/RelationshipExtractionV1Beta/RelationshipExtraction.swift
Source/RestKit/RestRequest.swift
Source/RestKit/RestToken.swift
Source/RetrieveAndRankV1/RetrieveAndRank.swift
Source/SpeechToTextV1/SpeechToText.swift
Source/TextToSpeechV1/TextToSpeech.swift
Source/ToneAnalyzerV3/ToneAnalyzer.swift
Source/TradeoffAnalyticsV1/TradeoffAnalytics.swift
Source/VisualRecognitionV3/VisualRecognition.swift
Tests/LanguageTranslatorV2Tests/LanguageTranslatorTests.swift
WatsonDeveloperCloud.xcodeproj/project.pbxproj

Updating all services to use a ResponseToError function. Also updated RestKit to remove compatibility with the original DataToError.

Updating services to use ResponseToError

---

Source/RestKit/RestRequest.swift
Tests/ConversationV1Tests/ConversationTests.swift

Check low-level error from response in RestKit

---

README.md

Updated all links to documentation to avoid redirects by leading to new Bluemix locations.  Also fixed a couple of bad doc links.

Update documentation links for new Bluemix locations.

---

Source/DiscoveryV1/Discovery.swift
Source/DiscoveryV1/Models/ConfigurationDetails.swift
Source/DocumentConversionV1/DocumentConversion.swift
Source/SpeechToTextV1/Models/RecognitionSettings.swift
Source/SpeechToTextV1/Models/Word.swift
Source/SpeechToTextV1/SpeechToText.swift
Source/SpeechToTextV1/SpeechToTextSession.swift

Service documentation was recently moved. #663 updated the links in the readme. This pull request  updates links in the source code documentation.

Update source code links to documentation

---

Package.swift

This pull request updates the `Package.swift` file for Swift 4. It also adds a notice about the Speech to Text and Text to Speech services that are unsupported with SPM.

Update Package file for Swift 4

---

.travis.yml
Scripts/run-tests.sh

This should update the build status badge to passing.
Ideally, the badge would indicate test success as well, but the integration tests are too inconsistent with live services. Will try to add mocking support in a future release.

Update Travis to build for Xcode 9.2 / Swift 4 / iOS 11.2

---

README.md
Source/DocumentConversionV1/DocumentConversion.swift

This pull request deprecates the Document Conversion service that was retired in October 2017.

Deprecate Document Conversion

---

Scripts/run-tests.sh

The most recent build of the swift-sdk failed because the Starscream framework could not be linked with Speech to Text. This pull request modifies the `run-tests.sh` script to build the dependencies using Carthage.

Rework run-tests.sh to build Carthage dependencies

---

Cartfile.resolved
Source/SpeechToTextV1/SpeechToTextSocket.swift

This pull request updates Starscream to v3.0.4 and modifies `isNormalDisconnect` for Starscream's new-and-improved error handling.

Update Starscream to v3.0.4

---

WatsonDeveloperCloud.xcodeproj/project.pbxproj

This pull request fixes a bug when there are spaces in the `PROJECT_DIR` environment variable.

Add quotations to the config argument for SwiftLint

---

Source/VisualRecognitionV3/VisualRecognition+CoreML.swift
Tests/LinuxMain.swift
Tests/VisualRecognitionV3Tests/VisualRecognition+CoreMLTests.swift

Fix Linux build with Core ML

---

Source/NaturalLanguageClassifierV1/Models/Classification.swift
Source/NaturalLanguageClassifierV1/Models/ClassificationCollection.swift
Source/NaturalLanguageClassifierV1/Models/ClassifiedClass.swift
Source/NaturalLanguageClassifierV1/Models/Classifier.swift
Source/NaturalLanguageClassifierV1/Models/ClassifierList.swift
Source/NaturalLanguageClassifierV1/Models/ClassifyCollectionInput.swift
Source/NaturalLanguageClassifierV1/Models/ClassifyInput.swift
Source/NaturalLanguageClassifierV1/Models/CollectionItem.swift
Source/NaturalLanguageClassifierV1/NaturalLanguageClassifier.swift
Tests/NaturalLanguageClassifierV1Tests/NaturalLanguageClassifierTests.swift
WatsonDeveloperCloud.xcodeproj/project.pbxproj

This pull request adds the `classifyCollection` operation along with an integration test.
The following commits used the previous API definition, but updated the generated source code to the latest style produced by the generator:
The following commits added changes introduced with newer versions of the API definition:

Add support for classifyCollection method

---

Source/DiscoveryV1/Discovery.swift
Source/DiscoveryV1/Models/Conversions.swift
Source/DiscoveryV1/Models/SegmentSettings.swift
WatsonDeveloperCloud.xcodeproj/project.pbxproj

This pull request updates the documentation and adds support for the new document segmentation settings.

Regenerate Discovery Service

---

Source/LanguageTranslatorV2/LanguageTranslator.swift
Source/LanguageTranslatorV2/Models/DeleteModelResult.swift
Source/LanguageTranslatorV2/Models/IdentifiableLanguage.swift
Source/LanguageTranslatorV2/Models/IdentifiableLanguages.swift
Source/LanguageTranslatorV2/Models/IdentifiedLanguage.swift
Source/LanguageTranslatorV2/Models/IdentifiedLanguages.swift
Source/LanguageTranslatorV2/Models/TranslateRequest.swift
Source/LanguageTranslatorV2/Models/Translation.swift
Source/LanguageTranslatorV2/Models/TranslationModel.swift
Source/LanguageTranslatorV2/Models/TranslationModels.swift
Source/LanguageTranslatorV2/Models/TranslationResult.swift

This pull request regenerates the Language Translator service. No new functionality has been introduced, but a large swath of code has been updated to the latest style used by the generator.

Regenerate Language Translator Service

---

Source/TextToSpeechV1/Models/CreateVoiceModel.swift
Source/TextToSpeechV1/Models/Pronunciation.swift
Source/TextToSpeechV1/Models/SupportedFeatures.swift
Source/TextToSpeechV1/Models/Text.swift
Source/TextToSpeechV1/Models/Translation.swift
Source/TextToSpeechV1/Models/UpdateVoiceModel.swift
Source/TextToSpeechV1/Models/Voice.swift
Source/TextToSpeechV1/Models/VoiceModel.swift
Source/TextToSpeechV1/Models/VoiceModels.swift
Source/TextToSpeechV1/Models/Voices.swift
Source/TextToSpeechV1/Models/Word.swift
Source/TextToSpeechV1/Models/Words.swift
Source/TextToSpeechV1/TextToSpeech.swift

This pull request updates Text to Speech to use the latest style produced by the generator.

Regenerate Text to Speech

---

Scripts/run-tests.sh

Update scripts to query for schemes, in relation to this issue: https://github.ibm.com/arf/planning-sdk-squad/issues/504

Initial automation of listing schemes

---

README.md

More explicit on WVR authentication

Documentation updates around WVR authentication

---

Source/AssistantV1/RestKit/JSONWrapper.swift
Source/ConversationV1/RestKit/JSONWrapper.swift
Source/DiscoveryV1/RestKit/JSONWrapper.swift
Source/LanguageTranslatorV2/RestKit/JSONWrapper.swift
Source/NaturalLanguageClassifierV1/RestKit/JSONWrapper.swift
Source/NaturalLanguageUnderstandingV1/RestKit/JSONWrapper.swift
Source/PersonalityInsightsV3/RestKit/JSONWrapper.swift
Source/SpeechToTextV1/RestKit/JSONWrapper.swift
Source/TextToSpeechV1/RestKit/JSONWrapper.swift
Source/ToneAnalyzerV3/RestKit/JSONWrapper.swift
Source/VisualRecognitionV3/RestKit/JSONWrapper.swift

This PR just removes some dangling symlinks that pointed to a RestKit file that was recently removed.

Remove dangling symlinks to JSONWrapper

---

Source/RestKit/JSON.swift
Source/RestKit/RestRequest.swift
Source/RestKit/RestToken.swift
Tests/RestKitTests/JSONValueTests.swift

In reference to this issue: https://github.ibm.com/arf/planning-sdk-squad/issues/312

Parse date-time properties into Date objects

---

Tests/DiscoveryV1Tests/DiscoveryTests.swift

This PR makes a few small changes that should make the Discovery tests more reliable.

Fix discovery tests

---

Tests/ConversationV1Tests/ConversationTests.swift

Convert Conversation tests for single completion handler

---

Source/VisualRecognitionV3/VisualRecognition+CoreML.swift
Tests/VisualRecognitionV3Tests/VisualRecognition+CoreMLTests.swift
Tests/VisualRecognitionV3Tests/VisualRecognition+UIImageTests.swift
Tests/VisualRecognitionV3Tests/VisualRecognitionTests.swift
Tests/VisualRecognitionV3Tests/VisualRecognitionWithIAMTests.swift

Initial pass at changing VR tests to single completion handler.

Convert VR tests to single completion handler

---

Source/TextToSpeechV1/TextToSpeech.swift
Tests/TextToSpeechV1Tests/TextToSpeechPlaybackTests.swift
Tests/TextToSpeechV1Tests/TextToSpeechTests.swift

This PR updates the TTS tests for the new single completion handler design.
It also includes a small hand-edit fix.

Update TTS tests for single completion handler

---

Tests/NaturalLanguageUnderstandingV1Tests/NaturalLanguageUnderstandingV1Tests.swift

Update NLU tests for single completion handler

---

CHANGELOG.md
README.md
Source/AssistantV1/README.md
Source/AssistantV2/README.md
Source/DiscoveryV1/README.md
Source/LanguageTranslatorV3/README.md
Source/NaturalLanguageClassifierV1/README.md
Source/NaturalLanguageUnderstandingV1/README.md
Source/PersonalityInsightsV3/README.md
Source/SpeechToTextV1/README.md
Source/TextToSpeechV1/README.md
Source/ToneAnalyzerV3/README.md
Source/VisualRecognitionV3/README.md

In the main README, I left the version (0.38.1) alone since that will be updated when I use bumpversion.

Update all READMEs and the CHANGELOG for 1.0.0

---

Scripts/travis/publish-documentation.sh
Source/SpeechToTextV1/SpeechToText+Recognize.swift
Source/SpeechToTextV1/WebSockets/RecognitionSettings.swift
Source/SpeechToTextV1/WebSockets/SpeechToTextSession.swift
Source/SpeechToTextV1/WebSockets/SpeechToTextSocket.swift
Tests/SpeechToTextV1Tests/SpeechToTextUnitTests.swift

Fixes https://github.com/watson-developer-cloud/swift-sdk/issues/938

Fix SpeechToTextV1 grammars and redaction for websockets

---

Source/AssistantV1/Models/InputData.swift
Source/AssistantV1/Models/MessageResponse.swift
Source/CompareComplyV1/CompareComply.swift
Source/CompareComplyV1/Models/Attribute.swift
Source/CompareComplyV1/Models/BodyCells.swift
Source/CompareComplyV1/Models/ContractAmts.swift
Source/CompareComplyV1/Models/Document.swift
Source/CompareComplyV1/Models/EffectiveDates.swift
Source/CompareComplyV1/Models/LeadingSentence.swift
Source/CompareComplyV1/Models/Parties.swift
Source/CompareComplyV1/Models/SectionTitles.swift
Source/CompareComplyV1/Models/TerminationDates.swift
Source/DiscoveryV1/Discovery.swift
Source/DiscoveryV1/Models/DocumentAccepted.swift
Source/DiscoveryV1/Models/DocumentCounts.swift
Source/DiscoveryV1/Models/DocumentStatus.swift
Source/DiscoveryV1/Models/Gateway.swift
Source/DiscoveryV1/Models/GatewayDelete.swift
Source/DiscoveryV1/Models/GatewayList.swift
Source/DiscoveryV1/Models/GatewayName.swift
Source/DiscoveryV1/Models/SourceOptionsWebCrawl.swift
Source/SpeechToTextV1/Models/Grammar.swift
Source/SpeechToTextV1/Models/Grammars.swift
Source/SpeechToTextV1/SpeechToText.swift
Source/VisualRecognitionV3/Models/Classifier.swift
Source/VisualRecognitionV3/VisualRecognition.swift
Tests/DiscoveryV1Tests/DiscoveryTests.swift

https://github.ibm.com/Watson/developer-experience/issues/6032
Regeneration of the SDK. Mostly contains minor updates to AssistantV1, CompareComplyV1, DiscoveryV1, and SpeechToTextV1.
There are 2 bug fixes that are technically breaking changes, but are included in a non-major release version because the code was never actually working (i.e. not returned by the service.
1. Removal of `additionalProperties` from `MessageResponse` in AssistantV1.
1. Change `BodyCell` property types in CompareComplyV1.

Release 1.4.0

---

.bumpversion.cfg
IBMWatsonAssistantV1.podspec
IBMWatsonAssistantV2.podspec
IBMWatsonCompareComplyV1.podspec
IBMWatsonDiscoveryV1.podspec
IBMWatsonLanguageTranslatorV3.podspec
IBMWatsonNaturalLanguageClassifierV1.podspec
IBMWatsonNaturalLanguageUnderstandingV1.podspec
IBMWatsonPersonalityInsightsV3.podspec
IBMWatsonSpeechToTextV1.podspec
IBMWatsonTextToSpeechV1.podspec
IBMWatsonToneAnalyzerV3.podspec
IBMWatsonVisualRecognitionV3.podspec
README.md
Source/SupportingFiles/Shared.swift

Finish the release process by hand because semantic release fell on its face.

Release version 2.0.0 [skip ci]

---

Source/TextToSpeechV1/TextToSpeech.swift

Don't know how this was missed first time through.

fix: missed metadata on other error [skip ci]

---

Source/VisualRecognitionV3/VisualRecognition+CoreML.swift

This PR fixes the hand-coded `classifyWithLocalModel` method to accumulate errors encountered by the concurrent classification tasks -- rather that immediately calling `completionHandler` with the error -- so that the completionHandler is only called once with the result of the method.

Fix multiple calls to completionHandler from classifyWithLocalModel

---

CHANGELOG.md
Source/VisualRecognitionV3/VisualRecognition+CoreML.swift
Source/VisualRecognitionV3/VisualRecognition.swift

PR with two small fixes to recent major release.

Release 2.0.1

---

.bumpversion.cfg
IBMWatsonAssistantV1.podspec
IBMWatsonAssistantV2.podspec
IBMWatsonCompareComplyV1.podspec
IBMWatsonDiscoveryV1.podspec
IBMWatsonLanguageTranslatorV3.podspec
IBMWatsonNaturalLanguageClassifierV1.podspec
IBMWatsonNaturalLanguageUnderstandingV1.podspec
IBMWatsonPersonalityInsightsV3.podspec
IBMWatsonSpeechToTextV1.podspec
IBMWatsonTextToSpeechV1.podspec
IBMWatsonToneAnalyzerV3.podspec
IBMWatsonVisualRecognitionV3.podspec
README.md
Source/SupportingFiles/Shared.swift

Finish the release process by hand because semantic release fell on its face _again_.

Release version 2.0.1 [skip ci]

---

Source/SpeechToTextV1/WebSockets/RecognizeCallback.swift

Signed-off-by: David Okun <david@okun.io>
This PR fixes #959 
No other information to add

Added public initializer to `RecognizeCallback`, fixes #959

---

CHANGELOG.md
Scripts/travis/publish-documentation.sh
Source/SpeechToTextV1/WebSockets/RecognizeCallback.swift
Source/SupportingFiles/Shared.swift
Source/VisualRecognitionV3/VisualRecognition+CoreML.swift
Tests/AssistantV1Tests/AssistantTests.swift
Tests/DiscoveryV1Tests/DiscoveryTests.swift
Tests/SpeechToTextV1Tests/SpeechToTextRecognizeTests.swift
Tests/VisualRecognitionV3Tests/VisualRecognitionTests.swift

Merge accumulated changes for Release 2.0.2 to master.

Release 2.0.2

---

.bumpversion.cfg
IBMWatsonAssistantV1.podspec
IBMWatsonAssistantV2.podspec
IBMWatsonCompareComplyV1.podspec
IBMWatsonDiscoveryV1.podspec
IBMWatsonLanguageTranslatorV3.podspec
IBMWatsonNaturalLanguageClassifierV1.podspec
IBMWatsonNaturalLanguageUnderstandingV1.podspec
IBMWatsonPersonalityInsightsV3.podspec
IBMWatsonSpeechToTextV1.podspec
IBMWatsonTextToSpeechV1.podspec
IBMWatsonToneAnalyzerV3.podspec
IBMWatsonVisualRecognitionV3.podspec
README.md
Source/SupportingFiles/Shared.swift

Finish the release process by hand because semantic-release fell on its face _again_.

Release version 2.0.2 [skip ci]

---

.github/ISSUE_TEMPLATE/bug_report.md
README.md
Source/AssistantV1/README.md
Source/AssistantV2/README.md
Source/CompareComplyV1/README.md
Source/DiscoveryV1/README.md
Source/LanguageTranslatorV3/README.md
Source/NaturalLanguageClassifierV1/README.md
Source/NaturalLanguageUnderstandingV1/README.md
Source/PersonalityInsightsV3/README.md
Source/SpeechToTextV1/README.md
Source/TextToSpeechV1/README.md
Source/ToneAnalyzerV3/README.md
Source/VisualRecognitionV3/README.md

This PR adds a "Featured Projects" section to the README and fixes doc URLs that pointed to console.bluemix.net to use the new cloud.ibm.com host.

Documentation updates

---

Source/AssistantV2/Assistant.swift
Source/NaturalLanguageUnderstandingV1/Models/Parameters.swift
Source/NaturalLanguageUnderstandingV1/NaturalLanguageUnderstanding.swift
Source/SupportingFiles/Shared.swift
Source/SupportingFiles/ibm-credentials.env
Tests/NaturalLanguageClassifierV1Tests/NaturalLanguageClassifierTests.swift
Tests/SpeechToTextV1Tests/SpeechToTextTests.swift
Tests/TextToSpeechV1Tests/TextToSpeechTests.swift
Tests/VisualRecognitionV3Tests/VisualRecognitionTests.swift
Tests/VisualRecognitionV3Tests/VisualRecognitionWithIAMTests.swift

This pull request refactors bluemix to cloud.ibm with the exception of demo links and links to apps running in bluemix.

Refactor bluemix to cloud.ibm

---

Source/SpeechToTextV1/SpeechToText+Recognize.swift

Add configureSession parameter to RecognizeMicrophone

fix(SpeechToTextV1): Add configureSession parameter to RecognizeMicrophone

---

CHANGELOG.md
IBMWatsonAssistantV1.podspec
IBMWatsonAssistantV2.podspec
IBMWatsonCompareComplyV1.podspec
IBMWatsonDiscoveryV1.podspec
IBMWatsonLanguageTranslatorV3.podspec
IBMWatsonNaturalLanguageClassifierV1.podspec
IBMWatsonNaturalLanguageUnderstandingV1.podspec
IBMWatsonPersonalityInsightsV3.podspec
IBMWatsonSpeechToTextV1.podspec
IBMWatsonTextToSpeechV1.podspec
IBMWatsonToneAnalyzerV3.podspec
IBMWatsonVisualRecognitionV3.podspec
README.md
Scripts/generate-documentation.sh
Scripts/travis/publish-documentation.sh
Source/SpeechToTextV1/SpeechToText+Recognize.swift

New Swift SDK release 2.1.1.  See CHANGELOG for details.

Release 2.1.1

---

README.md

docs(readme): fix 3.0.0 preview link

---

README.md
Source/SpeechToTextV1/WebSockets/SpeechToTextSession.swift
Tests/NaturalLanguageClassifierV1Tests/createClassifier.sh
Tests/SpeechToTextV1Tests/SpeechToTextUnitTests.swift
Tests/VisualRecognitionV3Tests/VisualRecognitionUnitTests.swift
Tests/VisualRecognitionV3Tests/createClassifier.sh

This pull request updates all instances of gateway urls to their onecloud equivalents.

Update gateway urls

---

Sources/DiscoveryV2/Discovery.swift
Sources/NaturalLanguageUnderstandingV1/Models/Features.swift

This PR should address any breaking changes that were previously committed

fix(discov2,nlu): fix previously breaking changes
